### ISSUE TITLE
Not having a way to remove or utilize taint kills the mod

### ISSUE THREAD

**Issue by Riounis** [Azanor/thaumcraft-beta#1002]
Note: This isn't really a bug, just some feedback on the current state of the mod. I personally haven't dealt with Thaumcraft at all, but a friend of mine on a server we have started to play with it, and very early on, before he was really even able to start crafting things, he nearly ruined our base with flux, taint, and rifts. He claims there's no early explanation of flux or taint in the book, and when we researched how to fix it, we found that you can supposedly put silverwood trees around it to contain it, but that didn't work, and other than that, we just had to spend a large amount of time (because breaking taint blocks is so slow) fixing the base. Then after that, the rift wouldn't go away, even when the flux was gone. It doesn't have to be easy for the player to obtain, but just a single item to remove rifts or break taint blocks more easily would go a long way towards the playability of this mod.

**Comment by LastXsile** [comment]
The methods for dealing with taint haven't been fully implemented as the mod is still in beta. In older version there was a few different ways to deal with it. As for now we will just have to wait and see what updates come up with in the future.

**Comment by ST-DDT** [comment]
Isn't it possible to kill the taint seedlings/worms and the taint will revert back to (almost) normal? Well I had to google that solution, so an ingame info would be nice.

**Comment by ziba1** [comment]
switch to creative and type in sponge in the search, theres a flux sponge that cleans the flux up that causes taint, you can give yourself that and switch back to survival, its cheaty, but for now it seems to be the only way to deal with it.  It is definitely annoying, ive heard that there is a plan for dealing with it being implemented soon.

**Comment by edhelday** [comment]
To maintain my base as clean as possible, i have search a mountain, the taller and wider i could find, then placed a distillery under it, at bedrock height, because the taintacles and flux appears on top of structures where taint are produced, so i had time to distil many, many materials until taint reached to subsoil.

**Comment by apmax** [comment]
A few points:
1. This mod is currently in beta, as you should clearly be able to see.  Many features are still being ported over from the old version, and many new features are still being changed and implemented.
2. There is a way to deal with and manage taint, simply kill the taint seed and all of the taint will dry up quickly.  Flux and flux rifts are currently undergoing some changes, but if you go back to around beta 13 or 14, flux rifts should quickly disappear after expending flux by spawning taint seeds.
3. If you're explicitly intending to submit feedback rather than report some kind of bug, this is not the correct place to do so.

**Comment by Reassembly** [comment]
- Planting essentia crystals in a flux-heavy area will soak up flux, whenever there's more flux than vis in the aura and the total flux+vis is higher than the natural level in that chunk. Remove the crystals when they turn purple, and use them to make Salis Mundus for fresh crystals.
- If there's no live taint seeds within range, tainted soil and stone will slowly revert to normal soil and porous stone. If you have regular taint outbreaks and a means to safely kill the seeds from range, the resulting porous stone can be _very_ profitably farmed for a variety of resources.
- When you're tired of drowning in free vis crystals/native clusters/amber/diamonds/etc, pointing a Stabilizer (powered by a Vis Generator) at the rift (aim at the middle/the thickest part) will slowly stabilize it, eventually causing it to _completely_ stop spawning taint seeds and flux effects. The rift won't go away, but it will be effectively disabled. Keep the flux levels down with planted crystals, and you should have no more taint at all.

**Comment by Riounis** [comment]
Thank you all for the advice, I'll link my friend to it. @apmax Where would be the correct place to submit feedback?

**Comment by Geethebluesky** [comment]
@Riounis [Suggestions repo](https://github.com/Azanor/thaumcraft-suggestions)
