### ISSUE TITLE
[B16](Bug/Suggestion):Problems with the wussmode / Configs / Black rifts doesnt disapear 

### ISSUE THREAD

**Issue by Wotzinator** [Azanor/thaumcraft-beta#1056]
as it seems the wuss mode is either not implemented yet or it doesn't work because things like the black rifts taint aggressive wisps and so on still spawn.also black rifts don't disappear no matter how long you wait (i didn't even cause any more taint in the area) but i still grows and spawns taint seeds around it. also some more configs for the wuss mode would be nice like which things you want to disable like the black rifts or taint. also a folder in the config folder for all the different thaumcraft config files.

**Comment by luminousinsect** [comment]
I'm also waiting forever for a deliberately created rift to despawn. I haven't messed with wuss mode because as in previous versions of Thaumcraft warp/taint/flux are required to achieve important research and progress in gameplay. I've seen reports somewhere of rifts being permanent as of B14, should this have been changed or is this deliberate? I would make a firm suggestion that they are not permanent because that would absolutely kill this mod for servers unless they want to give everyone a flux sponge.

Also once the flux in the area gets low enough (from enough "flux events" ie giant seeds/taint fountains spawning) the events should stop regardless of the presence of a rift since they do not have enough "seed flux" in the aura to use to spawn. I get this behaviour but wisps still seem to spawn. Also from what I understood there should be a setting the Thaumcraft config for the length of time a rift lasts after the flux in its chunk is reduced, but I'm not seeing this and I just regenerated my configs for B16.
