### ISSUE TITLE
Server unable to start: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle

### ISSUE THREAD

**Issue by jschrader00** [Azanor/thaumcraft-beta#1080]
I've been running this server for about  a month now and it happened to crash and is unable to start now. since I'm not sure what was occurring with players using Thaumcraft at the time, I apologize in advance but I have attached the server crash log since the Java exceptions looked pretty descriptory
[2018-06-30-3.log](https://github.com/Azanor/thaumcraft-beta/files/2152421/2018-06-30-3.log)

**Comment by ThorVonAwesome** [comment]
I've been running an instance of FTB Revelations 2.0 and this exact issue popped up when one of the players on my server placed a thaumcraft stabilizer because they heard it would help get rid of a taint rift. However, as soon as power was fed it, the server closed and is now stuck in a crash loop because its all in a loaded chunk. 

The crash log does not report the specific block that is causing the issue or the dimension. However, the player told me what dimension it was in so I cut the dimension folder out of the world and restarted the server and that fixed the problem for the time being. 
[crash-2018-07-02_11.15.28-server.txt](https://github.com/Azanor/thaumcraft-beta/files/2156800/crash-2018-07-02_11.15.28-server.txt)

**Comment by Azanor** [comment]
Update to B17+
