### ISSUE TITLE
[1.12.2] [beta17] Magic & Essentia Mirror are missing inventory icons

### ISSUE THREAD

**Issue by wamc2017** [Azanor/thaumcraft-beta#1088]
Hi,

the Magic & the Essentia Mirror are missing their inventory icons in beta 17.

![essentia](https://user-images.githubusercontent.com/33242447/42167882-a885cb8e-7e0f-11e8-9e70-77b548be6197.png)
![magic](https://user-images.githubusercontent.com/33242447/42167891-ae90d1ae-7e0f-11e8-8bc5-bb2e378d14be.png)

Thanks for looking into it.

Best regards
wamc

**Comment by Azanor** [comment]
It works perfectly fine for me. What other mods are you using?

**Comment by wamc2017** [comment]
Only Thaumcraft, Baubles and Forge.

Seems to be an issue with forge, it works fine until forge-14.23.4.2715, forge-14.23.4.2716+ got this issue....

**Comment by Glease** [comment]
It seems a fix is pretty straight forward. That PR made blockstate #inventory variant to take precedency instead of item model json. As suggested in that PR removing the duplicate definition of a model will resolve the issue. In this case removing the #inventory variant from blockstate json make everything fine.
I've tested my solution both on 2747 (a version I prefer) and 2705 (a recommended version). They are both working fine.

**Comment by Omnimetatron** [comment]
Still an issue in B23 [https://imgur.com/a/1Szizp9](url)

**Comment by seebs** [comment]
I don't know if this is the same thing, but I also see no icons on the corresponding research branches in the thaumonomicon?

**Comment by Glease** [comment]
The same. Research entry uses that model too.
