### ISSUE TITLE
[Suggestion] remove Vitium from early researches

### ISSUE THREAD

**Issue by Lohoydo** [Azanor/thaumcraft-beta#1103]
Right now a phial of Vitium is required for the essentia pipes research. The only sources for vitium are void metal items and taint items (or Experiment 115 if you have Twilight Forest).  While I'm all for needing to cause some controlled chaos of taint for voidmetal and other endgame items, forcing people to do so early on, when they may not even know how to, is a bit harsh.  I would recommend either adding another source of Vitium available fairly early or, even better, removing Vitium as a requirement early on.

**Comment by Mii1128** [comment]
There are the corrupted crystals. You can get them fairly early. But I do agree, Vitium is a pain. Expecially on the pipe research (wich you need to make the flux filter). Maybe replace it with something alse "volatile". Maybe tenebrae or mortuus. Former one being not that easy to get (obsidian is the best source i think). I want to play like a wuss outside wuss mode Azanor.

**Comment by Reassembly** [comment]
@Lohoydo  I don't know if corrupted crystals would be a viable early source of Vitium, considering that you need Vitium to make corrupted crystals. (Flux apparently does not taint crystal clusters, as of b17.)

It's possible to open a rift and cause a Taintsplosion fairly early - all you need is a crucible and a stack or two of something disposable. The issue I see is not that Vitium is too hard to get early on _as such,_ but that (1) if it's your first time playing TC6, it's kind of non-obvious that _that's_ how you get Vitium, (2) there's not much warning that you should do this a safe distance away from your primary base, and (3) if you're super-careful with not wasting essentia in the crucible, you might _never_ unlock the research node that directs you to overflow the flux in the first place.

(2) is somewhat mitigated now that rifts can collapse on their own now (once again), but the side-effects can still be very destructive (to the point that new players still regularly talk about rifts as though they were "bugs" in the mod itself that need "fixing"). (1) and (3) could basically lock someone out of progressing further, unless they look up spoilers or make a mistake - neither of which seems like an appropriate "key" to unlock further progress.

I think I agree that there ought to be a "safer" method of acquiring small amounts of Vitium early on. Again, I wonder why Vishrooms aren't being used for this purpose, or anything else. Speaking of Vishrooms...

@Mii1128  Tenebrae? Mushrooms. 😃

**Comment by niknight42** [comment]
Unless it changed from when I did it a week or so ago, mycelium in a mushroom island biome is a source of vitium, you just need a silk touch tool.

**Comment by belathus** [comment]
If you play with Twilight Forest, Carminite also has a good amount of vitium.

**Comment by apmax** [comment]
Personally I feel that requiring the player to encounter taint before advancing very much into the mod is a good thing.
Especially with how the flux and taint mechanics have changed and taint is no longer world-ending, it's a really interesting and fun progression step.  Even with the balance still being tweaked.

**Comment by CharCharthemonkey** [comment]
there is 1 really easy way to get any of the vis crystals at all with most mods by simply making a wisp farm

**Comment by Azanor** [comment]
As has been stated there are quite a few ways to get vitium. It is intended that you get some exposure to flux/taint along the way, but it is still possible to get vitium without doing that.

**Comment by cdfa** [comment]
If i'm reading this correctly, as of b19, the only vanilla way to get vitium is from mycelium, as it requires vitium to make a causality collapser or taint crystals and rifts don't collapse on their own. Mycelium is very hard to get in vanilla though, because it requires a ton of exploration and you need to get silk touch from either an enchantment table combined with quite a bit of luck or an xp farm or from the Thaumcraft enchanting (which i haven't looked into yet). I'm playing in a very small mod pack for performance reasons and I think Thaumcraft should not rely on other mods to make getting vitium not ridiculously hard.

Or am i missing something?

**Comment by cdfa** [comment]
I've experimented further and exploded a rift with a cheated in causality collapser and to my surprise it didn't spawn a taint seed, but just some void seeds and a primordial nodule... So still no vitium.

I've also tried just creating a ton of flux in the chunk and the rift grew huge, but didn't do anything except for spawning a few wisps and taint clouds that attacked me. There seemed to be so much flux that it got stored up in the chuck "invisibly", because it wasn't showing on the thaumometer, but after exploding the rift a new one spawned immediately and the flux maxed out. I repeated this a few times and then also cheated in the flux sponge and it took a few more clicks of removing all the flux in the area (which kept reappearing) before i could finally close the rift without having a new one spawn immediately.

While flying around i also discovered a rift in the middle of nowhere. Not sure if it's related...

**Comment by apmax** [comment]
Let taint happen.
Let a rift spawn, let a taint seed spawn, let it taint some soil, kill it, pick up the tainted soil.

**Comment by cdfa** [comment]
I gave it quite some time to do so (I chopped down a whole greatwood tree with an iron axe), but the only effects i got was wisp spawning and damaging flux clouds. It destroy a few blocks of dirt, but they just disappeared.

**Comment by apmax** [comment]
More flux.

**Comment by cdfa** [comment]
The thauminomicon also says the chances of having a rift collapse naturally are extremely small and that is releases it's energy in smaller puffs, but since that's the way I've read and seen so many people get taint I thought it should be possible nonetheless.

**Comment by apmax** [comment]
As far as I'm aware, a rift collapsing does not create taint, it has never worked that way.
A rift has a chance to spawn a taint seed as a flux event if there is enough flux.  You are intended to encounter this naturally to progress.

**Comment by cdfa** [comment]
Well, maybe a taint seed would spawn over a longer period of time if the rift is at someone's base where is continuously chunk loaded, but I don't want that mess in my base and I've seen many others complain about how it made their base impossible to live in. If it really is true that it takes a long time for a taint seed to spawn, getting vitium that way is apparently still quite difficult and dangerous, so I think there should be an easier more obvious way of collecting it. Maybe some way of capturing a part of the taint cloud that rises when emptying a crucible or getting it from filters on the essentia smelter?

I like how the player is encouraged to experiment with large amounts of flux, but they should be told it could be dangerous and they should not have to sit around their rift for more than 5 minutes before they get a significant result.
