### ISSUE TITLE
Cannot insert items into an essentia smeltery using most methods

### ISSUE THREAD

**Issue by belathus** [Azanor/thaumcraft-beta#1123]
Golems, hoppers, and Mekanism's logistical transporters work.

I tried inserting fuel into the bottom of a smeltery using a dispenser without any success; items just get thrown all over. So far, I've tried EnderIO's item conduit and item buffers, ImmersiveEngineering's conveyors, and Random Thing's item collector.

**Comment by Lohoydo** [comment]
I did some further testing on this, and can confirm the conveyor and EnderIO issues.  Additionally, EnderIO conduits don't even connect to the smeltery, as though its not an inventory.  Additionally, Thermal ducts will connect to both bottom and sides, but is erratic as to what it will transport.  
For example:
Coal will go in the bottom but not the sides (coal is also weird due to the lack of aspects, don't know if that affects anything)
charcoal will go in both
alumentum will go in both
nitor will go in both even though it is not a fuel
vis crystals will not go in either

**Comment by Azanor** [comment]
Most of my inventories do not support the new forge capabilities system which is probably the reason for this. I will implement it at some point, but it is not a priority at the moment.
Honestly mods with inventory management things like pipes should check for both the old and new systems. The few inventory management things I have (like golems) checks for both.

**Comment by Azanor** [comment]
I have done a rough capabilities implementation for b20 which should solve this issue.
