### ISSUE TITLE
[B17] Manually placed Vis Crystals do not spread

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#1139]
I am not sure weither or not this applies to naturally generated ones, too, or if this even is intentional (the generation stat only allows clusters of generation 3 and lower to spread).
If it is intentional and for manually placed clusters only, I want to request the option to harvest single shards from the cluster, because otherwise manually placed clusters serve little purpose.

**Comment by Reassembly** [comment]
I've managed to build a crystal farm in which crystals have successfully spread to new clusters. Crystal spread is much slower than cluster growth, but it eventually _does_ happen under the right conditions. Freshly-planted crystals do seem to be "generation 1", so generation shouldn't be a limit until you reach the edge of a large patch of extended growth.

<details><summary>More Info</summary>
Part of the trick is building a 3D lattice of stone blocks for the crystals to grow within. Ideally, _every_ air block in the lattice should be orthogonally adjacent to _exactly_ one stone block, and diagonally adjacent to as few stone blocks as possible. These conditions maximize the chance that any given attempt at crystal spread will be successful (provided that Vis levels are high enough to trigger an attempt at spread).

For comparison, a crystal planted on a flat stone floor with a ceiling higher than two blocks has 27 possible locations to spread to - but nine are blocked by stone, nine have no stone next to them for the crystal to attach to, and one is blocked by the source crystal itself, so only 8 of 27 attempts to spread will be successful. At least one tileable space-filling arrangement exists which raises the odds to 22 in 27, and there are arrangements which raise the odds to 25 in 27 for the first-generation cluster to spread (but less for second-generation and further). In other words, setting up a proper "growth medium" for crystals can approximately triple the speed at which they spread.

Then, you "merely" have to repeatedly cycle the Vis using SIlverwood trees, Vis Batteries and a redstone timer, holding the Vis at least 10 units above its natural level as frequently and for as long as possible - but not _too_ high, or the Vis starts degrading into Flux. I say "merely" because it's easy to do crudely, but looks like it'll be a pain to optimize. Still, even a crude 80-second on/off timer connected to a couple of Vis Batteries has got me enough crystal spread to be worth harvesting - though I wouldn't have bothered if quartz wasn't so dangerous to harvest with my currently-installed mods. Making Vis crystals in a Thaumatorium is _so_ much faster and easier, _if_ you have the quartz for it.
</details>

**Comment by MalkContent** [comment]
And you did that in the current version?
I tried spreading vitium crystals and vis crystals, pumped their chunks full of flux/vis and did not get them to spread (grow? yea. spread? no :c). I've been waiting for literal hours. :/
Granted I only tried growing them on pillars, so they could only spread upward/downward, but still.
I'll try giving them more growth options.

**Comment by Reassembly** [comment]
Yep, b17, current version. It took a while for the crystals to start spreading, but not hours...more like several minutes, cumulatively across a few Vis cycles, from 12 fully-grown clusters scattered around the chunk. I assure you it's possible, if not very practical.

**Comment by MalkContent** [comment]
Huh. Welp. Turns out this is just painfully slow :x
1/16th of the speed of regular growth and then the additional x/27 chance on top of it with x being the number of valid places to grow to. So say you just plant this on a stone plane like someone not looking this stuff up too much, you'd have 8 free spaces, spreading would be 1/16 * 8/27 = a 1/54th of the growth rate.
Imo 1/16th spread rate compared to growth rate alone is enough to be sufficiently slow. Maybe rerun the random position that it tries to spread to until it finds a suitable new position. Give it a 1/16th chance or something to not rerun every loop, so it preserves a chance to fail due to lacking space.
I made a thing on wolfram alpha where you can get your chance to fail due to lack of space. a is chance to fail every loop, b is number of actually valid places to spread to.
http://www.wolframalpha.com/input/?i=solve+a*(sum+(((27-b)%2F27)%5Ei)*((1-a)%5E(i-1)),+i+%3D+1+to+infinity)+where+a+%3D+1%2F16,+b%3D8

tried to plot it for forever but apparently i am exceeding computation time :/
for reference with a=1/16:
b=25 -> chance to fail \~0.5% vs current \~7%
b=16 -> \~4% vs \~41%
b=8 -> \~13% vs \~70%
b=4 -> \~26% vs \~85%
b=2 -> \~44% vs \~93%
b=1 -> \~62% vs \~96%

**Comment by Azanor** [comment]
Yup, it is super slow. If I made it any faster than worldgen crystals will take over the world :p

**Comment by MalkContent** [comment]
but the spread is limited by the generation, no?

**Comment by Azanor** [comment]
Not really - the aura can naturally go over the normal baseline limit now during the full moon.

**Comment by MalkContent** [comment]
No, I mean that crystals can't spread if their generation is too high. The thing where newly spawned clusters have 1 generation higher than the cluster that spawned them.
