### ISSUE TITLE
(Suggestion)Rebalancing the infusion system

### ISSUE THREAD

**Issue by Wotzinator** [Azanor/thaumcraft-beta#1168]
since thaumcraft 6 it is nearly impossible to perform infusions because they get unstable way to fast no matter what im doing most things wont work because of this. as an example i cant use thaumic enchantments because firstly it wont take the enchanted books and also the items are knocked of way to fast.

**Comment by Reassembly** [comment]
Changes are supposedly coming that should make infusion stabilization a little easier. In the meantime, one way to counteract items being knocked off pedestals is to connect some hoppers to your pedestals and load them up with spare items (of the same type). If something gets knocked off by instability, it'll be instantly replaced by the hopper, allowing the infusion to continue.

Also, there's been some analysis done on the infusion stability mechanics in the comments for #1115, that might give you a little more help with finding a way to stabilize your infusions.

**Comment by wamc2017** [comment]
https://github.com/Azanor/thaumcraft-suggestions is maybe the best place for suggestions...

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#374

**Comment by katzenpapst** [comment]
Something should be done allright.

I kinda see the point of getting rid of the classical candle rooms, but not really of the currenty necessary 5 stabilizers with 25 generators. These steampunk-y devices look a little out of place in an infusion room IMHO. Not to mention the fact that they aren't even nearly enough...

I think the altar needs better stabilisation items, so that instead of placing a sh*tload of cheap items, you need a few, but expensive ones.

- Like, special infusion candles, made with maybe ender pearls and blaze rods. They need to be infused and have High instability themselves.
- Or, a special weapon to behead enemies in such a way, that the heads they drop work better than vanilla mob heads.
- Or, a candle mounted onto a skull, like in that one gravestone mod. Requires the infusion candle from before to be infused into a skull, then grants an even greater bonus.

Or something somewhat different. A different kind of stabilizer, which makes stabilizing light, but destabilizes the altar if placed too close. The light then needs to be redirected using relays (like the vis relays in earlier versions) into the altar. 
Explanation could be like: it drains reality around it, and shoots it out in the direction it's turned, so that reality at the target gets thicker, and around the device thinner.

This could have some side effects on the surrounding area. Increased mob spawn rate, certain special mobs spawn (endermites?), and rifts form at even lesser taint levels. Maybe you also get more warp effects, as the eldrich abominations from the void have less of a barrier between them and you.
