### ISSUE TITLE
Can't chop down silverwood tree with iron axe

### ISSUE THREAD

**Issue by HFinner** [Azanor/thaumcraft-beta#1182]
Attempting to destroy a silverwood log with an iron axe does not work, it takes it forever to break and nothing is dropped. While on the other hand you can literally use your hand to harvest it faster and be able to collect it. I know this is a small thing but I just want to help perfect the mod :)

**Comment by Hallowizer** [comment]
I had the same problem, but I realized it was because I had a tree chopping mod active. It is probably because of your tree chopper. Turn it off when you are breaking the tree, and it will chop normally. The tree chopper wants it to take longer so it cuts the whole tree, and your axe probably didn't have enough durability to cut the whole tree.
