### ISSUE TITLE
[Bug] Pickaxes in Arcane Bore with "Destructive" Infusion don't have 50x durability

### ISSUE THREAD

**Issue by TuckV** [Azanor/thaumcraft-beta#1229]
As stated in the title. The arcane bore usually uses pickaxes at 1/50th their normal rate (as described in the book) but with the Destructive infusion, the 8 extra blocks mined per break are counted for their full durability damage, making Destructive pickaxes extremely fragile in the bore.

**Comment by TuckV** [comment]
Also - the extra blocks mined are simply deleted.

**Comment by Azanor** [comment]
Yup, I fixed that as well.

**Comment by Ulysses2** [comment]
Burrowing is bugged as well - both the closest and furthest ore block are destroyed and only one item drops.

Also, this is really minor but Destructive and Burrowing aren't listed under the "Other properties:" heading in the GUI.

Collector doesn't seem to do anything but I don't know if it should since it's kind of built in by necessity.
