### ISSUE TITLE
[B13->B19] Server Hanging on "Stopping Aura Thread for Dim _"

### ISSUE THREAD

**Issue by tikoxi** [Azanor/thaumcraft-beta#1230]
I've ran almost every beta version clear back to B13 and my server gets stuck at the same point. None of the threads about this issue have a workable solution, and I've no idea how to make it work. It only seems to stop the aura threads properly for 3/5 dims (dimensions?)  before it hangs, and leaving it doesnt seem to help. I left it overnight at one point, only for the server to tell me it was overloaded and had skipped 300,000 ticks.
[latest.log](https://github.com/Azanor/thaumcraft-beta/files/2253686/latest.log)
What am I missing?

**Comment by Azanor** [comment]
That is technically not what is causing your server problems. That message displays after the server has attempted to shut down for some reason. Something else is causing the actual problem. Unfortunately it is not obvious from your logs. Have you attempted removing mods one by one to see what is maybe causing the issue?

**Comment by tikoxi** [comment]
Sorry, I didn't quite make it clear: this log is still from server boot. At 9:31, I put in the server stop command. At 9:17 was the freeze. Everything after that is normal server shutdown. The previous few lines before I told it to shut down are what it stalls on every time. It will open aura threads for about 5 different dimensions, does done work with then, but only shut down 3 of them before stalling. I can try cycling mods to see if there is a conflict somewhere, I've just been testing different versions so far

**Comment by galaxy119** [comment]
I've been having a similar experience since updating from B17 -> B20, thaumcraft loads up all the aura threads for every DIM on the server after the spawn area is prepared (this is not a changed behaviour from B17 and previous) however, as soon as all of the aura threads are started, the server stalls for between 120,000-240,000 ms (2-4mins). During which time the server can be pinged by players but connections result in a Timed Out error, and no console input is registered. 

After the server stall ends, FML then unloads all of the unused DIMS (everything except 0 and -1) and Thaumcraft removes the aura cache for each DIM as it's unloaded, after all DIMS are unloaded by FML, Thaumcraft then stops the aura threads for the unloaded DIMs, a console message such as the following appears `04.08 09:09:52 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 222735ms behind, skipping 4454 tick(s)` then the server begins to run normally.

From what I can tell through the console, nothing procedure-wise has changed from using earlier versions of Thaumcraft (B16/17). The same actions take place in the same order after the same amount of time, up until the server stall after starting the Aura threads for every DIM. After the stall finishes, server actions proceed as expected on a similar timetable to when they did before the update.

Downgrading thaumcraft back to B17 does eliminate this bug.


Perhaps something in the way B19+ loads the aura threads? Or perhaps it's a forge bug with how it handles loading/unloading DIS during/after server startup?

**Comment by tikoxi** [comment]
I have the opposite experience. I upgraded to thaumcraft 20 and while this behavior continues, the server is joinable instead of resulting in perpetual timeouts.

I've got nothing for explanation, but it's working :/

**Comment by galaxy119** [comment]
The server *is* joinable, after a very long initial stall period after the aura threads initialize, as stated, downgrading back to B17 fixes the issue, but I've yet to try B18/19 as of yet. For now I'm sticking with B20 and just eating the extra startup time on the daily restarts.

**Comment by galaxy119** [comment]
I failed to check the forge version actually installed on the server, i figured perhaps the forge running on the server was outdated, but it's the same as the version you updated to, so I'm abit confused. Will updating forge break all of my current mods?

**Comment by F9Alejandro** [comment]
It isn't exactly upgrade, but more a downgrade. As it is stated newer versions of forge have the issue, same with what happened in one version of sevtech where the end was bugged. Try using a version or 2 older to see if that it is indeed the newer versions.

**Comment by Xoulious** [comment]
I'm still having this exact issue, is there any fix since the thread has been closed?

**Comment by connorch** [comment]
Also seeing this issue here on Thaumcraft-1.12.2-6.1.BETA26, has anyone found a fix for this?

**Comment by StrayCargo** [comment]
Also encountering this issue in my current version of thaumcraft with sponge forge hanging the server. 
Thaumcraft-1.12.2-6.1.BETA26
spongeforge-1.12.2-2838-7.2.1

**Comment by Jamiemundy** [comment]
I think I may know what might be causing the issue but I am not fully certain this is the issue. So this is a bit of an isolated situation with one mod but it could be any mod that messes with the moon for all I know. I've taken notice that anything that messes with the moon in Minecraft with thaumcraft around. Like for example, a blood moon mod causes world or server crashes because the aura is not regenerating or accepting anything in that matter. Whenever I was doing some thaumcraft related stuff like polluting the atmosphere with flux while a blood moon is going on. It just crashed my world and removing the blood moon mod stopped the crashes entirely or at least adjusted a setting in the blood moon mod config to have the red moon set to false. But what I am thinking here is that if anything is messing with the moon in Minecraft. The aura freaks out, decided to cease to exist or refuses to have any new vis be regenerated, or refuses any flux in the atmosphere. So as a result since the flux had nowhere to go, it just crashes the world entirely instead of adding onto the atmosphere. During a blood moon I did bring out my thaumometer before I did anything and it showed the current pollution and vis in the aura and no crash, it is when I started polluting the aura is when it crashed.

This is just what I have observed and thinking about what may be causing this issue. 

https://gyazo.com/22f97c509fa3af9dd3cbbdd287e851fb
