### ISSUE TITLE
Alchemical metallurgy not completeable if started in older version? [B21]

### ISSUE THREAD

**Issue by runfalk** [Azanor/thaumcraft-beta#1281]
I researched Alchemical metallurgy in B17. I stopped at step 3/3 since Void metal wasn't implemented then. Today I updated to B21 and progressed a lot towards the Eldritch research. I created a Causality collapser that I used on a rift and got 10 void seeds, but scanning them didn't unlock any research.

If I look in the Eldritch tab it says the Void seeds research is blocked by Alchemical metallurgy. This doesn't seem intentional.

This looks similar to #1187 but that seem to have been marked as resolved.

I worked around the problem by granting myself the research using `/tc research nickname METALLURGY`.

![2018-08-11_02 52 17](https://user-images.githubusercontent.com/864128/43986560-da9e0740-9d12-11e8-9f22-b3051d4d859d.png)

![2018-08-11_02 52 27](https://user-images.githubusercontent.com/864128/43986561-dc417b86-9d12-11e8-854f-7e73ebc06ad8.png)

**Comment by Reassembly** [comment]
This _type_ of issue (not necessarily this specific issue) seems to come up often enough that it seems like there needs to be some means of detecting (and automatically repairing/regressing) invalid states/dependencies in the research tree - at least until TC6 is out of beta, and the research tree is less likely to dramatically change every few versions.

Or at least, a way to manually "forget" a research node (so that it can be re-researched and properly trigger new research nodes) that doesn't require jumping into Creative mode and/or enabling cheats and/or going into the save files with an NBT editor.
