### ISSUE TITLE
possible dimension ID conflict with Welcome to the Jungle Mod in the future

### ISSUE THREAD

**Issue by ben-mkiv** [Azanor/thaumcraft-beta#1294]
Hi,

noticed that theres already a config option for the outer lands in the beta configs, which is preset to -42.

actually theres a mod "welcome to the jungle" which already uses the same dimension id.
so to not run into conflicts i would suggest to chose another dimension id.

Welcome to the Jungle Mod => https://minecraft.curseforge.com/projects/welcome-to-the-jungle

**Comment by aaronhowser1** [comment]
That mod has less than 10k downloads, while most Thaumcraft 6 versions have over 100k. Wouldn't this be better for Welcome to the Jungle to fix? A modpack maker could also just change the config themselves.

**Comment by ben-mkiv** [comment]
ThaumCraft doesnt use the dimension yet, while there are servers which already use dimension id -42 with welcome to the jungle mod. Changing their dimension ID would break all those setups.

so its less likely to cause problems if thaum just chooses another id -.-

**Comment by F9Alejandro** [comment]
How long has this mod been out? also just how many servers do you know that use this mod over TC?

This seems more of an issue with server owners and miss configured packs then it does as an actual mod issue.

Can the "Welcome to the jungle" mod have the dim id changed? also most mods use positive id numbers then negative ones.

if this is such a big issue then change the configs yourself then hounding the mod authors about something that the end user already has access to change. If @Azanor really wanted to have that id only for TC then there wouldn't be a config option to change it.

**Comment by ben-mkiv** [comment]
what a nice attitude.... :-1:

**Comment by F9Alejandro** [comment]
Thank you for your opinions, although everyone is entitled to one doesn't mean you should push it on to others. It isn't difficult to regen that dim and change the TC config for that dim id, Azanor knows that people want to be able to change it because of this issue where mods have same ids for dims instead of getting one assigned upon world gen. (would be a cool feature for forge).

Going off on people because they respond to you with the reasons why things are the way they are is not helping you and puts more on the people who are supporters of the mod and the people who work on it. Please think about the different perspectives and decisions made before going off on people because they don't want to make changes that would take away from more pressing development (like bug fixes and other issues)

**Comment by F9Alejandro** [comment]
It really didn't since Azanor isn't the one to respond, I am not working for him or with him. I really like this mod and wish for it to continue. Getting vexed over something that is meant for clarification not only for you but for others as perceived from what is provided to the players and mod developers, will not help you any more than the next person that gets upset because the mod developer (Azanor) decided on something and has given all players access to change with little to no difficulty.

Basically you are getting upset because you don't want to take effort into making a simple change that will fix your issue. What you are trying to convey is being muddled by your unwillingness to see it from others points of view. Out of all the issues posted on this issue tracker, only a few have had major issues or conflicts with other mods. Your case isn't justified as Azanor has already provided the means to rectify this issue.

If this is about issues with a modpack then contact the modpack author to see this issue page as it will tell them all they need to do to fix the conflict of dimension ids. Please note that the mod you are claiming to have massive issues with is still fairly young and isn't as mainstream as some of the older more publicized mods such as this one and many others.

Everything being said Azanor was correct in closing this as there is no point in adding a change when it can already be changed by the end user. It is the end user that chooses not to take advantage of it. There is no reason to continue the hostility when everything has been explained to you twice and your to ignorant to actually think it over and actually even attempt what was given as a solution.

___Any further responses @ben-mkiv I will ignore unless it is a serious question and not rude/indignant towards others/myself___

**Comment by ben-mkiv** [comment]
its not about me or you, its about OTHER PEOPLE who arent that familiar with reading minecraft logs and which will require additional help to fix this in the future. You obviously didnt get it.

**Comment by F9Alejandro** [comment]
Then if they have an issue with it in the future if some how they use the two mods together that they make in there own custom type modpack they can always make an new issue and we will point them to here as it has the answer to their question/issue. Most people that make modpacks have at least some know how of configs and logs.

It will be rare for people to get a modpack that doesn't already have the configs modified so it works correctly. Only time it does is when someone who is new to making packs or are making it for themselves, then they will have questions or issues and can always ask others for help (kind of the point of a community is to help each other).

What you are trying to prove is becoming more pointless than ever as you keep saying others yet you are the only one complaining and trying to get a rise out of others. You still keep bringing up that changing the default for the dimension id will fix conflicts, however it won't there will still be conflicts as other mods take over vanilla functions and inject into them. Example enderio was recently having an issue with TC and was causing crashes, turns out it was fixed and the mod wasn't updated in that modpack which contains the fix.

Trying to prove yourself to others yet getting very defensive when there is no reason to makes it seem that it is only yourself that you really care about and that you don't want to change a simple config and regen that specific world dimension.

___Piece of advice people don't like being told what to do and how they should do it, take it from me I am a hobbyist programmer and like to try and figure things out on my own and reach out when i need help. forcing someone to do something that you are already given the option of is not helpful in the least and is extremely counter productive, if it is some sort of enhancement then it would be added to the list of things to look into. What you are trying to do is a demand and not a request, you are not asking you are stating.

Think before you respond to this. ___

**Comment by ben-mkiv** [comment]
Thanks, i write mods on my own, and i take suggestions like this and fix my shit.

**Comment by F9Alejandro** [comment]
good for you, but why "fix" something that isn't broke, and why attack someone who is only trying to make you understand. I know i make mistakes and i try to fix them to the best of my ability. I will not force others to make changes only ideas and suggestions.
