### ISSUE TITLE
[B21] Infusion Stabilizer non-functional on multiplayer server

### ISSUE THREAD

**Issue by Deiarch** [Azanor/thaumcraft-beta#1295]
I recently started hosting my own multiplayer server on my computer. I have found that the infusion stabilizer does not work in multiplayer, but it does in single player with identical setups. An appropriately placed and powered infusion stabilizer gives me neither any effect on infusion stability nor any particles. I attempted to power it with 1-4 Vis Generators at first, but I also tried a Stirling Generator from EnderIO. Neither worked in multiplayer. 

To rule out problems caused by other mods, I created a clean server with only thaumcraft/baubles installed. I got the exact same results. The stabilizer was functional in single player but non-functional in multiplayer.

I'm wondering if it is possibly related to #969 or #1068. It's not crashing like #969 nor will re-logging or F3+A chunk reloading fix it, like it #1068.

Forge server 2745
[latest.log](https://github.com/Azanor/thaumcraft-beta/files/2281161/latest.log)
[debug.log](https://github.com/Azanor/thaumcraft-beta/files/2281162/debug.log)

From my clean install (probably a bit easier to read)
[debug.log](https://github.com/Azanor/thaumcraft-beta/files/2281163/debug.log)
[latest.log](https://github.com/Azanor/thaumcraft-beta/files/2281164/latest.log)

**Comment by Nuclearfarts** [comment]
Relogging wouldn't fix it if it's in the spawn chunks, so it could be the same as #1068. Try restarting the server.

**Comment by Deiarch** [comment]
I've restarted the server numerous times in this process. No dice.

**Comment by Nuclearfarts** [comment]
OK, I was having the same problem. Turns out that the stabilizers actually are working, but won't generate particles. There a few commands to check this if you're opped. Use `/blockdata matrixX matrixY matrixZ {}` and one of the values listed will be stability. With stabilizers, this should be about 12 (plus or minus a bit because of floating point errors.) If you want to make sure they're working, do `/blockdata matrixX matrixY matrixZ {stability:0f}` and use the first blockdata command to check the stability and make sure it's going back up to 12.

**Comment by Deiarch** [comment]
Good call. It is, in fact, only a particle issue and not a functionality issue.
