### ISSUE TITLE
Infusion stabilizers not working?

### ISSUE THREAD

**Issue by KamiSami** [Azanor/thaumcraft-beta#1347]
So i recently got back in Minecraft after little break and i remember infusion working just fine before, but now im getting very dangerous results even that im using same setup i did before, and it wasn't dangerous at all, no purple lightnings like now, i rechecked several times my candles and heads being mirrored with the other side of the matrix.. Im pretty sure it's right. https://imgur.com/bN0a7g8

**Comment by yunruiwatts** [comment]
@KamiSami when posting an issue, please make sure to mention which version you are currently running.

In this case, the issue is that there is a cap on how many candles and skulls you can use to stabilize your infusion - having more than 12 doesn't do anything. You should look into using the (somewhat new) stabilizers that use RF. They're on the infusion page in the Thaumonomicon.

**Comment by KamiSami** [comment]
Ah right, completely forgot.. Though, i doubt that matters anymore. I definetily should've checked the thaumonomicon first, was too convinced it being bug at first experience.. Thanks, i think i see the issue now.
