### ISSUE TITLE
Unable to use spells in dimensions other than Overworld

### ISSUE THREAD

**Issue by ToasterTricks** [Azanor/thaumcraft-beta#1348]
Saw a similar post about this [https://github.com/Azanor/thaumcraft-beta/issues/446](here). The issue was marked as a bug and done but no solution was listed.

Someone let me know what I am doing wrong, could not find a config option that would enable or disable anything based on dimension other than structures.

**Comment by ToasterTricks** [comment]
Bump!

Any info on how I can fix this? My friend and I really want to use the spells in The End and in The Nether.

**Comment by ToasterTricks** [comment]
!! I was able to fix this by reverting from Beta 8 down to Beta 7 !!

Unfortunately the mechanics for foci are a bit different and it seems they got broken in the transition from 7 to 8.

Also, you lose the grappling hook going down to 7 from 8.

But foci spells work in all dimensions in Beta 7

**Comment by Serifina** [comment]
You are _extremely_ far behind in versions. That's a bug that was long since fixed. The beta is not being updated further for 1.10.2 - all updates are now on 1.12.2. You should not be playing on 1.10.2 any longer anyway - the overwhelmingly vast majority of mods for it have been updated to 1.12.2. Either work your way up to that version of Minecraft, or stay on Beta 7.
