### ISSUE TITLE
Thaumium Fortress Helm

### ISSUE THREAD

**Issue by meitangdehulu** [Azanor/thaumcraft-beta#1354]
There may be problems with mask craftting .
Detailed in the figure.
http://i67.tinypic.com/nly5hl.jpg
http://i67.tinypic.com/2lufmex.png

**Comment by TechnoTadhg** [comment]
Same for Verdant Charms

**Comment by chuggafan** [comment]
That looks fine to me? It's showing that you get the same level of durability in/out for your thaumium helm before/after the goggles of revealing. I can at the very least attest to being able to craft the fortress helm in b17, and the visuals there seems to not have changed since then.

**Comment by wamc2017** [comment]
Doesn't the recipe work for you? You can use any Thaumium Fortress Helm and upgrade it, I think the book only shows one combination...

**Comment by wamc2017** [comment]
> There may be problems with mask craftting .

Sounds for me like an issue with crafting/the recipe, that's why I asked if the recipe doesn't work with any Fortress Helm. 
The recipe isn't wrong, you can use a Fortress Helm with Goggles on it and attach Goggles again (doesn't make any sense but it's not wrong), so the only issue is, that the Thaumonomicon only shows this one solution (instead of cycling through the different sorts of combinations)
TC doesn't add JEI support for infusions, that may be an issue with Thaumic JEI...

**Comment by TechnoTadhg** [comment]
I think Thaumic JEI might just copy its recipes from Thaumcraft itself, so if it was fixed in TC it would probably fix TJ as well. Either way yea it's a visual problem with items that can be used to make themselves.

**Comment by Azanor** [comment]
I did some testing and this bug only occurs if you have Thaumic JEI installed. They must be doing something naughty with the recipes.
