### ISSUE TITLE
Issues with mechanics and suggestions

### ISSUE THREAD

**Issue by AzraelTWC** [Azanor/thaumcraft-beta#136]
Can hear other peoples warp explosions.

boots of the traveler durability spam from nearby player wearing them.

The vis system is ridiculously unforgiving, everything you do creates flux and thus increases taint probability.

I think balancing needs done, and I think early mechanics need to be in place to filter flux.

Maybe nodes can exist rarely in the environment. Even rarer are pure nodes which cleanse the environment.  the player can then jar these up and use them in their bases to slowly cleanse it over time.

**Making taint and flux equalize in chunks is an important feature which should be added sooner than later as it would help with testing and balancing. 

Vis usage for items seems to be bugged or at the very least hard to read, crafting something with 50 vis doesn't have a noticeable decline that I can tell in the aura.

-Ideas for nodes-

Nodes become extremely rare, with even rarer traits. They have more uses than typically recharging vis, in fact only one has the capabilities.

Pure node - Cleanse Environment

Smart Node - A node which moves around and is tricky to capture. (placing a bookshelf or dropping books which it consumes, causes it too investigate where you can then jar it.) Can be place in jar and the jar can be placed near table to slowly regenerate inspiration. 

Vacuous Node - Nasty ones which act as a vacuum, sucking everything and anything into its center. Used primarily as an obstacle. Maybe the player can use an item for it to suck up and neutralize it. Allowing them to jar it up and create a mob trap.

Tainted Node - Node that generates flux, the opposite of a pure node in respect. Jar it up to contain it. These nodes make the most powerful version of tainted land, as removing the node is as important as destroying the seed.

**Comment by LordPinkerton** [comment]
I really don't see flux creation as unforgiving. I usually settle my base in chunks with roughly 250+ vis and after a solid playthrough of the content, only have at most 4-5 points of flux in the environment. You may need to consider using the flux reducing additions to your machines like venting ports and bellows and don't overburden the vis usage either. Always keep an eye on the available vis and don't let it get too low, as this, as far as I'm aware, also produces flux. The only times I have an issue with flux is when I accidentally drain a bottle of essentia. All of this is still being reworked, as far as I know, and it's still up in the air if nodes will make an appearance again, but as they stood in alpha, they were very problematic.

**Comment by Goof245** [comment]
Flux isn't a problem if you already know the mod and wait until you have the required efficiency tools in place before leaning on the aura. For a new player, perhaps someone who's never actually played TC before, it's a completely different story.

If someone's playing through the mod, happily abusing the aura with their level 1 smeltery and perhaps a level 1 furnace, they're going to rather quickly pile up on the flux in that chunk. Accidental spillage while learning to use the crucible / jars accelerates this. Without the flux draining away into the other chunks, they're going to have a giant taintsplosion eventually, possibly turning them away from the mod altogether.... Not a great "new player experience"...

We _need_ a flux - scrubber type block that can lower local flux, unlockable preferably right when flux entries start appearing in the the thaumonimicon. Alternatively, have the flux actually drain away into other chunks over time. If this is supposed to happen now, it's bugged, since in all my playthroughs flux just keeps rising up to 80-150 in a chunk and staying there.

**Comment by LordPinkerton** [comment]
At that point, you're asking for a risk/reward system to be without any risk. And as far as not being new player friendly, the literature in TC quite explicitly calls out flux as a byproduct that is best to be avoided and ways to monitor and mitigate it in multiple instances. And lastly, flux is just a part of Thaumcraft as much as warp is. It's going to happen, but easily, and I repeat, EASILY avoided in the numbers as to require you to move a base. In your example, there is no way you could have attained a 80-150 flux level in a single chunk without TRYING to get that much. The only times I had a problem that large was during the alpha stage of the mod, and that was because of issues with nodes and flux. In fact, I'm going to redo my entire single player world and go through with absolutely no regard for flux upgrades on my machines. I'll still avoid overburdening the vis aura, as I'm not wanting to TRY and create flux, but simulate as you say a "new player experience".

**Comment by Azanor** [comment]
The first two are issues that I will look into. 
I think the flux/vis balance is _ok_ at the moment and easily managed if you know what you are doing. Saying that, there will eventually be more mechanics in place to mitigate flux.

**Comment by Azanor** [comment]
Hmmm, exactly what do you mean by boots of the traveler durability spam?

**Comment by AzraelTWC** [comment]
Sorta like the harness icon popping up constantly on the left side of the screen. Someone n my server was wearing the boots and their icon was popping up over and over on the left side with a durability bar below.

**Comment by Azanor** [comment]
Was it popping up on other peoples screens or just theirs? It is supposed to show on the wearers screen to show the amount of charge it has.

**Comment by AzraelTWC** [comment]
Someone else was wearing it. It was constantly spamming on my screen when
near them. I was in creative. They were not.
