### ISSUE TITLE
[Beta 23] Vanilla items missing aspects still

### ISSUE THREAD

**Issue by Mario90900** [Azanor/thaumcraft-beta#1370]
Unfortunately, I had hoped that the Beta 20 update would fix this, but it appears that a few mods are still managing to glitch out the aspects on some vanilla items. I am running a large amount of mods in a pack I put together, but I did not have enough time to fully figure out what is causing the issues. I was able to determine that Natura still appears to be causing Rotten Flesh to lose its aspects, while another mod or mods are causing Cobwebs to lose aspects and likely their crafting recipe in alchemy as a result, along with just Oak Wood, while all other wood types are unaffected. This appears to translate into all Oak-based products lacking aspects as well, from aspect calculations. I hope to be able to test this more tomorrow, but I wanted to get the issue posted now as I had some information already.

**Comment by Glease** [comment]
You may want to report these to Natura and "another mod" instead. Azanor can't do much without resorting to extreme measures if other mods mess up aspects.

**Comment by Azanor** [comment]
Yup, unfortunately not much I can do at this point. There are ample help and warnings in the API for addon devs to not do things in certain ways, but if they choose to ignore that I cannot really prevent that.

**Comment by Hubry** [comment]
Twilight Forest people noticed a few TF aspects being missing despite being registered in an instance with just TF and TC (see https://github.com/TeamTwilight/twilightforest/issues/498#issuecomment-417254171).

From debugger investigation by a TF dev bs2609, it seems to be casused by Thaumcraft itself inferring aspects from some item's aspects, which causes it to look at recipes for that item, ending up looking at an unregistered item's aspects, and setting them to an empty aspect list.
Later the item with wildcard metadata (32767) is registered, but future lookups don't even look at that because it was registered with no aspects by the lookup process.

In TF's case, giant logs were looked up when trying to register torch aspects (giant logs produce 64 planks, planks produce sticks), and later giant logs are registered with wildcard metadata.
