### ISSUE TITLE
vision modules for golems

### ISSUE THREAD

**Issue by audiosalix** [Azanor/thaumcraft-beta#1376]
i don't really understand how the vision modules are supposed to work for the golems. i have a golem with a seal set to harvest and collect crops, and since I gave him a vision module in theory it should work for my whole farm (within 48 block range). but it only seems to work within the 8x8x8 range restricted by the seals themselves

what's the point of being able to add an extra module for them  if they're still restricted by the seal range?

**Comment by lOmicronl** [comment]
Don't you mean "thirty-six seals", since a 48x48 area translates into a 6x6 grid of 8x8-area seals? ;)

Also, some golem applications are not restricted by seals. Golem Logistics, for example, allow you to order a nearby golem to go fetch an item from storage for you. Having extra range on such golem assistants is very useful.

**Comment by Azanor** [comment]
Yup, the range is how far the golem will travel to perform something.
