### ISSUE TITLE
Not able to progress - mod doesn't recognize crafted items?

### ISSUE THREAD

**Issue by Zerahar** [Azanor/thaumcraft-beta#1378]
I have a problem, which has occurred in two research branches now. I'm stuck in Basic Auramancy, because the mod doesn't recognize that I have crafted the Blank Lesser Focus. The same issue happened with Essentia Smelting, as the mod doesn't see that I have crafted the Essentia Smeltery. I've tried to craft the items multiple times, spawn them too, have them in my inventory when looking at the book and having them elsewhere. I play on a private server and I'm the only one using the mod currently.

**Comment by lOmicronl** [comment]
Crafting the Blank Lesser Focus works for me in my test world. Check out issue #1372 - there was a progress blocker encountered there due to the presence of an incompatible Thaumcraft addon. Whatever causes this, it's likely part of your install.

**Comment by LemADEC** [comment]
My understanding of the issue is that thaumcraft progression isn't detected, hence preventing progressing in new researches, when:
A- using Salis mundis on a crafting table,
B- using scribbing tool on a research table,
C- making tallow or leather in a cauldron.

Issue A is reproduced in SMP on Forge 1.12.2-14.23.4.2758+ with
- CustomNPC 26aug18 only installed client side,
- Thaumcraft Beta23 + Baubles 1.5.2 installed on both client and server side,
- no other mods.

Issue A is NOT reproduced:
- in single player with CustomNPC + Thaumcraft + Baubles (no other mods)
- in multiplayer with client and server having Thaumcraft + Baubles (no other mods)
- in multiplayer with client and server having CustomNPC + Thaumcraft + Baubles (no other mods)

On a side note, CustomNPC is adding a systematic capabilities on all ItemStack, including 'air'.

(wip)
