### ISSUE TITLE
Am unable to craft anything related to Thaumcraft?

### ISSUE THREAD

**Issue by Jitdy687** [Azanor/thaumcraft-beta#1380]
When using Thaumcraft, I can manually use items through creative mode, but when I try to craft these same items, it just doesn't register. I have reinstalled Thaumcraft in my mod folder, I have deleted the configs, I have tried Thaumcraft by itself (as I am using multiple mods), and I have tried multiple worlds, all with the same result. Any help would be appreciated, and if I am just being stupid and the fix is painfully obvious and is not a bug, then I apologize for wasting your time. If you need additional information, I will gladly provide it. Here, just in case, is my mod list along with their versions, included with which is my version of Forge. All the mods should be up to date as of August 24th.
https://pastebin.com/Q0TN6VjU

**Comment by Glease** [comment]
This question may sound a bit werid, but have you actually played Thaumcraft before? Do you know anything about Thaumonomicon? Your description sounds as if you haven't completed all those researches yet...

**Comment by lOmicronl** [comment]
To expand, the vast majority of Thaumcraft's recipes require Thaumcraft's own crafting station, or even more exotic methods of assembly (alchemy or infusion crafting). And you only learn how to make that crafting station, and how those other methods work, if you go through the mod's progression, as guided by the mod's own "quest book".

In order to get said book, you need to mine a naturally occuring vis crystal. They're generated all over the place where there is blank stone, and can be broken by hand. Once you do, you get an onscreen message. If you happen to have missed that message, the next step after that is to sleep in a bed.

**Comment by Jitdy687** [comment]
That sounds about right. Sorry, I am just starting with Thaumcraft, but the problem I was encountering was that I was using the wiki, which only mentioned making a wand as the first step. Thanks for the reply.
