### ISSUE TITLE
Arcane workbench won't craft certain items.

### ISSUE THREAD

**Issue by Sleeplless** [Azanor/thaumcraft-beta#1384]
For some reason the arcane crafting bench won't craft the focal manipulator. I've already done the research but it just won't work leaving me unable to progress is there a way to solve this?

**Comment by wamc2017** [comment]
Did you check if enough vis is in the aura and have you checked if the crystals needed are inside the workbench? Do other recipes work? Which version are you playing?

**Comment by Sleeplless** [comment]
I'm playing version 1.12.2  and everything is in place.

**Comment by wamc2017** [comment]
I meant the Thaumcraft version... Can you make a screenshot?

**Comment by Sleeplless** [comment]
Its version 6.1 Beta 23

**Comment by TechnoTadhg** [comment]
open the workbench with the ingredients inside and take a screenshot

**Comment by Azanor** [comment]
Do you have enough crystals for the recipe?

**Comment by MRDRMUFN** [comment]
I'm having the same issue from BETA17, included with FTB Revelation 2.3.0. I've attached screenshots below of attempts to craft alchemical construct, and void jar, both of which have been researched prior. 

<img width="662" alt="screen shot 2018-09-17 at 9 45 39 am" src="https://user-images.githubusercontent.com/544022/45630642-b4559580-ba5e-11e8-9352-e7d2402e3752.png">

<img width="851" alt="screen shot 2018-09-17 at 9 45 22 am" src="https://user-images.githubusercontent.com/544022/45630654-b881b300-ba5e-11e8-93f7-db4c1e8cb538.png">

**Comment by MRDRMUFN** [comment]
Just updated the server to Revelation 2.5.0 Beta which includes TC B24. And attempted to craft a void jar and alchemical construct again with the same results. Also tried moving the crafting table to new chunk.

<img width="458" alt="screen shot 2018-09-18 at 12 36 43 pm" src="https://user-images.githubusercontent.com/544022/45705684-d96e0500-bb3f-11e8-8246-d572fcdf5cf8.png">

**Comment by MRDRMUFN** [comment]
So far it's only those two recipes that I've encountered. The only thing in common between them is that they both require Perditio, though I was still able to craft the Caster's Gauntlet.

**Comment by Azanor** [comment]
Hmmm, could you maybe do me a favor? Try uninstalling ThaumicJEI and/or "Thaumcrafft inventory scan" temporarily and see if it still happens.

**Comment by MRDRMUFN** [comment]
Alright, so I've tested the following conditions:
- Removal of both TC-JEI and TC-InvScan in both single player and multi player. (experienced the problem only in multiplayer)
- Fresh map in multi player (no issues)
- Server map in single player (experienced the problem)
- Also tested granting all research on the server map in single player (still experienced the problem)

The bug seems to only appear from the current state of our map. I've also tried crafting in the Nether in case this only affects our Overworld dimension, but encountered the same issue. If you are willing to further investigate this issue, I've linked a copy of our server directory which includes the world causing issues below.

[https://drive.google.com/file/d/1Q1Nw6UmXluMxZ0Lqq1e6Y8Q9e0TWMBu-/view?usp=sharing](https://drive.google.com/file/d/1Q1Nw6UmXluMxZ0Lqq1e6Y8Q9e0TWMBu-/view?usp=sharing)
