### ISSUE TITLE
Thaumatorium just not working.

### ISSUE THREAD

**Issue by JudgeHiraeth** [Azanor/thaumcraft-beta#1460]
Hi, 
I'm using Thaumcraft 6.1Beta24 for minecraft 1.12.2. 
The Thaumatorium just doesn't seem to work, with either essentia tubes or emptying essentia transfusers.
I'm assuming this is not normal. I haven't read anywhere that the Thaumatorium has a specific input other than 'don't input through the output'.

**Comment by Amelia-** [comment]
It works fine for me with the emptying essentia transfuser but a requirement is to place the transfuser directly on the Thaumatorium with no tubes in between or it gets clogged.
The Thaumatorium requests more essentia than it actually needs and it can get clogged if there is no way to get the excess essentia out of the tubes.

**Comment by lilolbear** [comment]
B24 is working for me. I have not used transfusers but I have a pretty complicated series of pipes that connect the Thaumatorium to all the different jar types. 

The only reserved side is the front output and screen. When the pipes are connected, it should be pretty obvious. When you are trying to make something you can tap them with the resonator and you should see 128 suction at the first pipe. That ought to be enough to pull from any jar assuming you are using standard pipes.

**Comment by lOmicronl** [comment]
For troubleshooting purposes, try replicating this setup:

https://i.imgur.com/ePotado.jpg

It's about as simple as it gets - and, it is _impossible_ to clog up. Trust me, I tried. You can connect whatever jars you want to this, you can open or close the valves in any order, it doesn't matter. It just works, period. Heck, you probably don't even need the valves, but I have them because I thought I would.

If this setup doesn't work for you, _then_ you definitely have a problem. But I suspect your issue lies with the unintuitive way the Thaumcraft pipes work, which is clogging up your lines. Thus, separating the lines entirely should circumvent the issue.

**Comment by JudgeHiraeth** [comment]
![2018-10-02_08 03 45](https://user-images.githubusercontent.com/43742337/46318428-c8ca8e00-c619-11e8-9f40-73afc9a13f7a.png)
So this shoud work right? I tried making it literally as simple as it can possibly get but the Thaumatorium just refuses to accept any essentia through tubes or transfusers.

**Comment by lilolbear** [comment]
Nope. You have one pipe in there that has the blue collar around it. That one is a one-way pipe that is facing the wrong direction

**Comment by JudgeHiraeth** [comment]
@lilolbear I tried with just a normal pipe and also with a collared pipe facing either way, it still wasn't working :(

**Comment by lilolbear** [comment]
@JudgeHiraeth It looks like your Crucible doesn't have a fire under it. Stick a nitor under there and I'll bet all your troubles go away.

**Comment by JudgeHiraeth** [comment]
Ah, of course. The problem is simply that I'm just an idiot. Thanks for your help guys!
