### ISSUE TITLE
Config option to disable matrix durability

### ISSUE THREAD

**Issue by LIONEye** [Azanor/thaumcraft-beta#1467]
There is a config option in TC6, which allows you to disable flux, taint and such stuff. This things are not the real problem for me.
In one of the Beta versions a Matrix Stability-Durability system was added. It is very annoying and makes TC very boring to play.  
So I came up with an idea for config command, when set to True, would make all matrices in the thaumcraft to be always in their basic stage of stability. This means that they won't lose any stability after an infusion is complete, and won't gain any more stability from sources like candles or stabilizers. The infusions would always be in their default stability and, for example, high infusion would be high, no matter of how many infusions you've done before without pause.
Your wuss,
LIONEye

**Comment by lOmicronl** [comment]
I don't think infusion works the way you think infusion works...

The instability rating of "moderate" or "high" or the like is a measure of the increase of instability over time. It is not a measure of how bad the instability effects are. If you do a "negligible" infusion and somehow manage to let the matrix fall into "dangerously unstable", you will get exactly the same negative effects as a "very high" infusion would give you if the matrix was sitting in "dangerously unstable". The only difference between them is how fast the stability of the matrix degrades.

If you disable the degradation of the matrix, you get into a situation where all infusions are always stable, regardless of their rating. Okay, that could be a useful feature for people who just want to play around without any consequences. Heck, for all I know, setting "wussMode = true" in thaumcraft_misc.cfg might _already_ do this. I've never tried it out.

But if you introduce a system where "negligible" infusions are always stable, but higher difficulty ones are always unstable, you run into problems. For starters, there are more infusion stability ratings than there are matrix stability categories. The matrix knows "very stable" and "stable", but the former is irrelevant, because it only represents a buffer against gradual degradation; and it knows "unstable" and "dangerously unstable". So, three relevant states. Meanwhile, you have five difficulty levels of infusions currently accessible, and I believe there is even a sixth level among content not currently accessible. And even inside each rating level, there can be large differences in actual difficulty. You just cannot map that to matrix conditions. It doesn't work.

And even if it could work: an infusion in the "dangerously unstable" category is borderline impossible to finish. You can pull it off if it falls into that near the end, and you get very lucky; but if it starts out that way, you can forget it. The altar in this state will actively destroy your ingredients while flooding the room with poison, dealing damage to you, and pumping flux into the aura. Note that some high-end infusions take several minutes to complete, during which you would have to constantly be fighting against all these effects. Like... there's a "high" instability recipe that has a nether star on the outer ring of pedestals. Do you enjoy the idea that you have to carry 15-20 nether stars with you, just so you can replace it again and again and again whenever the unstable matrix randomly decides to melt it into poisonous goo?

I think, at this point, investing the effort to learn how to use powered infusion stabilizers is a lot smaller than the effort involved in playing with this proposed config setting of yours... =P

**Comment by LIONEye** [comment]
You are actually right. My idea isn't perfect and it would be even worse. Still I don't understand why infusion is so expensive to stabilize an infusion (36 diamonds to only make the Speed Stones). The TC4 version was not interesting too, but in a modpack based around only one mod with new content it is very expensive mostly in terms of aura damage.

I think that this is only a problem of Beta and I hope that in the next updates Az would not actually ease the infusion process, but do something about restoring aura.

**Comment by Azanor** [comment]
This has been closed, but I though I'd mention that infusion stability is getting completely reworked for the next update (b26).

**Comment by LIONEye** [comment]
Good to hear, but TC6 Beta25 can't even start.
