### ISSUE TITLE
1.12.2-6.1.BETA25 Crashed

### ISSUE THREAD

**Issue by sirohigan** [Azanor/thaumcraft-beta#1504]
Thaumcraft has crashed.
It crashes when the loading screen is over.
I have something to use in combination, but even a single unit will crash.

Windows10-64bit
1.12.2-forge1.12.2-14.23.5.2768
Thaumcraft-1.12.2-6.1.BETA25.jar
Baubles-1.12-1.5.2.jar

https://gist.github.com/sirohigan/58c6a0cc043d78005824eb1943320a89

**Comment by lOmicronl** [comment]
It is great that you come to make a bug report with logs and version info. However, please also take a short moment to quickly google your problem, or check other issues already on the tracker. Doing so would have revealed that this has already been reported quite often. It is due to a recent change made by Forge, requiring mods to adjust (Thaumcraft isn't the only victim).

Solution: downgrade Forge to below 2766, or wait for Beta 26, which will deliver the required adjustment.
