### ISSUE TITLE
Alembics filling slowly 

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#224]
Not sure if this is intended behavior or not - essentia seems to only fill the bottom alembic when you place more than one on top of the smeltery. After one type of essentia has been exhausted from the slurry tank in the smeltery, the second alembic begins to fill if there is another type of essentia. In previous versions, I feel like the alembics behaved slightly differently? I might be misremembering.

**Comment by Goof245** [comment]
Miiiiiight be intended behaviour. We now have those auxiliary slurry pumps to allow for parallel processing of essentia.

**Comment by NerdimusPrime** [comment]
I had four alembics stacked on top of the smelter and, even when I put items with multiple essentia types in the smelter, never saw essentia in any alembic except the one directly on top of the smelter. I tried this with both regular and thaumium smelters, with the same result. I was using emptying/filling transfer...things (forgot the actual name) on all the alembics, rather than tubes, so I don't know if that made a difference.

When I added an auxiliary slurry pump + transfer thing, essentia would come out of both the first alembic and the slurry pump, but still nothing from the other alembics. I'm not sure about this being intended behavior; stacking alembics should still be a viable option, because auxiliary pumps and flux vents compete for connections on the smelter.

**Comment by Goof245** [comment]
That's the idea though? You need to choose between faster parallel processing of essentia, or a much cleaner smelter. 

In TC5 at least, alembics behaved much the same as they do now:
![screenshot 140](https://user-images.githubusercontent.com/3851003/35815089-72f197a4-0ae3-11e8-9104-ed4d73032127.png)

More alembics =/= faster processing speed. Maybe in TC4 they processed through the entire alembic stack at once?

In TC6 you currently have 3 options:

 - Use alumentum instead of coal / charcoal
 - Attach bellows to the smelter to speed up essentia processing
 - Attach auxiliary slurry pumps to the smelter to process more essentia in parallel

**Comment by NerdimusPrime** [comment]
Oh, I completely agree about the need for a choice, sorry I didn't make that clear. What I mean is, before we can get the research for auxiliary pumps, our first option for parallel processing of items with multiple essentia types is stacking alembics, and that doesn't seem to be working properly.

Using my goggles, I never see essentia appear in any alembic except the bottom one of the stack, whether I have anything attached to the smelter or not. Nothing comes out of the transfer things attached to the other alembics either, so it's not like the essentia is entering and leaving the other alembics too fast for me to see with the goggles, because the animated "stream" from the transfer thing is pretty slow, and I'd definitely see that in the air.

**Comment by Goof245** [comment]
Is the problem that no essentia ever flows in to your other alembics? It should pick an alembic, start filling that one with a random type of essentia until there's no more of that type left, then start filling another one if it's available.

If you're pulling out the essentia as fast as it's being produced there is zero point in stacking more alembics.

**Comment by NerdimusPrime** [comment]
Hmm, ok, I must have been expecting TC4 behavior, before essentia transfusers. I remember that multiple alembics would start filling almost simultaneously, rather than filling one alembic with one type of essentia completely, before moving on to the next. Given the speed of transfusers in TC6, one alembic doesn't get to fill up to max so, like you said, multiple alembics never need to fill. Thanks for clearing that up.

I think I'll just stop reporting anything that doesn't generate a crash log, because I'm clearly terrible at this. lol

**Comment by Azanor** [comment]
Nope, this is how it is supposed to work. Stacking alembics simply increases your storage. You need the pumps to speed it up.
