### ISSUE TITLE
Caster, sanity and vis bar overlaping

### ISSUE THREAD

**Issue by mujmajnkraft** [Azanor/thaumcraft-beta#245]
When you are holding thaumometer or sanity checker in main hand and caster's gauntlet, thaumometer or sanity checker in off hand, their bars are overlaping. When you are holding caster's gauntlet in main hand and thaumometer or sanity checker in off hand, texture of the bars starts glitching.

Overlaping texture:
https://i.imgur.com/A9HQt7K.png

Broken texture:
https://i.imgur.com/MxteBDE.png

**Comment by MainFreak** [comment]
This is probably a bit offtopic but may I ask for a way to move around UI elements that Thaumcraft adds, whether ingame like The One Probe or in a config outside of the game wouldnt't really matter. A lot of mods like the corners TC usually occupies (for example WAILA, The One Probe, Harvest Festival and Blood Magic) so moving around some elements would be an awesome feature. Probe and Waila already allow moving around their own parts, no idea about Blood Magic but Harvest Festival does definetly seem to not allow moving it's Calendar Feature.

**Comment by twothe** [comment]
Being able to move the TC UI elements would be really appreciated. As soon as you have a few UI mods installed, TC elements tend to overlap others.

**Comment by Zarepheth** [comment]
I'd also like to move around the UI elements. I've not yet had Thaumcaft UI elements interfere with each other, but I've certainly had them interfere with (or be interfered with by) other mods' UI elements.

I just placed a request for Everlasting Abilities' UI effects to be freely positional, and since they were interfering with Thaumcraft's UI elements, I figure I ought to make the same request with Thaumcraft.

https://github.com/CyclopsMC/EverlastingAbilities/issues/100
