### ISSUE TITLE
Cannot unlock Infusion Enchanting research

### ISSUE THREAD

**Issue by Zero-ui9** [Azanor/thaumcraft-beta#256]
The infusion enchanting research is requiring a sharpness 1 book, however it does not accept the one I have in my inventory. I notice the text colour of the one in the book is light blue, as opposed to the one in my inventory(and all other enchanted books I have) is yellow, so I would assume this is just an NBT problem.

http://puu.sh/zkZzS/9c9862f6c8.jpg
https://puu.sh/zkZvx/bc5e734d2a.jpg

I did /not/ have this problem with the auromancy "break" research with the silk touch and fortune books, though I did that research in beta 3

**Comment by Goof245** [comment]
If you look through the code in the .jar, the NBT Azanor is looking for is identical to that of books you manage to enchant yourself. It's also the same as books you spawn yourself using commands, so I'm not really sure what the problem is here :(

**Comment by Zero-ui9** [comment]
the NBT he is looking for is clearly not identical, sure the NBT for what enchant it is may be the same but the info for the colour of text in the item name is not. In fact I've seen similar problems in a different mod where you could obtain an enchanted book with blue text and you couldn't even use it in an anvil(granted that was in 1.7.10, but the point still stands that the NBT is not the same)

**Comment by Goof245** [comment]
Text colour makes no difference, it's ONLY looking at the NBT tag.

This gives a book that satisfies the Infusion Enchantment research:
`/give @p minecraft:enchanted_book 1 0 {StoredEnchantments:[{lvl:1,id:16}]}`

Swap id and lvl in that command and you get the exact same book functionally, but it is ignored by the Thaumonomicon.

The astute will notice the book still has yellow text, as have all `minecraft:enchanted_book`s (item ID 403 apparently...). Yet the Thaumonomicon still accepts it.

Player - crafted books seem to have very slightly different tags, either with id and lvl swapped or with s appended to one or both of them. Neither of these slight changes please the Thaumonomicon.

With the fortune II book, additional tags seem to be there referencing `repair cost` if the book was formed by two fortune I books combined in an anvil. Result is as previously reported; unhappy Thaumonomicon.

**Comment by taggedjc** [comment]
Why would the Sharpness I book not be working, then?  It can't have been made in an anvil.

**Comment by Goof245** [comment]
*Either* with id and lvl swapped *or* with s appended to one or both of them.

**Comment by Zero-ui9** [comment]
having just spawned a book with the command you gave, it still is not accepting it. Also doing /give @p minecraft:enchanted_book 1 0 {ench:[{lvl:1,id:16}]} does give a book with blue text, but its still not useable(in fact that book isn't even useable in an anvil).

**Comment by Goof245** [comment]
The `ench` tag is for applying enchantments to items, the `StoredEnchantments` tag is specific to `enchanted_books` and specifies that the book contains an enchantment fit for applying to another item. 

What that first command gave you was not a valid book, it is an `enchanted_book` that contains no actual enchantments, but has itself been enchanted with sharpness I. If there are other mods out there that create and use these "blue text" `enchanted_book`s, then their mod authors have likely made the same mistake. (perhaps intentionally, so the books can't be used in a normal anvil?)

The fact that you and I require the swapped `id` and `lvl` to get our own Thaumonomicons to accept our books is puzzling. Az really needs to be checking if the tag for the required enchants exists on the item, not just looking for that exact item. (since the ways in which you gain a fortune II book can result in different items, especially if the book has more enchantments than just fortune II)...

**Comment by Zero-ui9** [comment]
all I did was I looked in the assets, found the research.jsons, and that was the data tag it had listed. I don't know if he changed it between beta 3 and 4, but I'm on 4

**Comment by Azanor** [comment]
I've "fixed" the missing s twice now. I seem to keep missing some.

I do agree the system needs a bit more flexibility, but that is easier said than done. I will take another look at it though.

**Comment by Azanor** [comment]
I've managed to get the system to be a bit less picky. Any item with any number of enchantments will qualify as long as the required enchantments are present. Even items with higher level enchantments of that type will qualify.
