### ISSUE TITLE
Tainted tentacles can glitch, becoming unkillable but constantly in the "damaged" state. Might disable mob spawning

### ISSUE THREAD

**Issue by tablesix** [Azanor/thaumcraft-beta#274]
In the nether on our server, there is a tainted region that has quite a few tentacles growing. At least 5-6 of these are constantly being injured by some ghost force. None of these are dying, and they don't seem to react to arrows. Others are killable, however. Coincidentally, our nether no longer seems to spawn mobs, other than from spawners. I'm thinking it's possible the two are linked. I believe I'm on the most recent public beta (1.10.2-6.0.BETA4.jar)

**Comment by Goof245** [comment]
What's the flux reading in there? Tainted seeds take damage if they're trying to spew taint in an area with 0 flux, perhaps the taintacles are the same.

**Comment by tablesix** [comment]
I'm not sure if these are seeds or tentacles. They're the noodle things that spew some particle effect, both the larger and smaller ones. The flux level is a little over 40 for some of them, and above 20 for another couple.

**Comment by twothe** [comment]
I guess they don't react to arrows, because entities are briefly invulnerable to damage after taking a hit. If they get constantly hit with 0 damage, they are constantly in this state of invulnerability.

Minecraft has a limit of mobs that can spawn on a server, which a single player can already reach. A direct effect of that is that in places that you rarely be in mobs don't seem to spawn at all. Especially the Nether tends to favor Pigmen over everything else.
