### ISSUE TITLE
[B6] Mod incompatibility: Storage Drawers

### ISSUE THREAD

**Issue by twothe** [Azanor/thaumcraft-beta#305]
I noticed several issues when using Thaumcraft Beta 6 together with the (popular) Storage Drawer mod:

- When placing a store seal on a Drawer Golems ignore it.
- When using the Break Focus (with Plan, not sure if that is relevant) the Drawer will not be broken but it will be dropped nevertheless, which allows you to infinitely duplicate the Drawer.

**Comment by Goof245** [comment]
First is not a bug, storage drawers do not expose an inventory. Use a Controller Slave block for that.

Second is.... interesting xD

**Comment by twothe** [comment]
Well, every other pipe or transport mod can put items into the drawer (not necessarily out).

**Comment by Azanor** [comment]
My guess is they 100% use the capabilities systems instead of IInventory. Currently I only support IInventory. I will need to redo my inventory handling for the 1.12 update which is when I will add support for both.

The duping issue has been reported for other blocks as well and is fixed for the next release.
