### ISSUE TITLE
[BETA6]Crash on Loading

### ISSUE THREAD

**Issue by rewanit** [Azanor/thaumcraft-beta#314]
[crash-2018-02-16_17.50.36-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1731726/crash-2018-02-16_17.50.36-client.txt)

**Comment by twothe** [comment]
The issue is related to the mod PSI, which registers potions in [ModRecipes@250](https://github.com/yrsegal/PSIonic-Upgrades/blob/master/src/main/java/wiresegal/psionup/common/crafting/ModRecipes.kt) as [PotionHelper.ItemPredicateInstance](https://skmedix.github.io/ForgeJavaDocs/javadoc/forge/1.11.2-13.20.0.2228/net/minecraft/potion/PotionHelper.ItemPredicateInstance.html)

**Comment by twothe** [comment]
Probably a bit too early to close this, there might be other mods that would cause a crash issue like this.

**Comment by MagusLucius** [comment]
And it also happens with Railcraft Creosote
