### ISSUE TITLE
[Improvement] Everfull Urn should not be an infusion recipe

### ISSUE THREAD

**Issue by twothe** [Azanor/thaumcraft-beta#315]
The Everful Urn is a nice tool to save you some time on the Crucible, however to craft it you need to have an Infusion Altar setup. For that you need to have at least a basic alchemy setup to power it. And from that it is only a small step to the automated Crucible that no longer requires the urn. So essentially: once you can craft the Everful Urn you no longer need it.

I suggest to turn the recipe to an artifice recipe that does not require infusion.

**Comment by Goof245** [comment]
Or a crucible recipe; flowerpot + aqua + praecantatio + vacuos = urn. Or something like that...

**Comment by taggedjc** [comment]
There is still potentially a reason to use the Crucible instead of using the Thaumatorium : there's no waste.

When you use the Thaumatorium, you necessarily have to use an Essentia Smelter, which means some of the essentia from items you smelt will actually end up lost, so you need more items to melt down on average.  Using the Crucible instead, you can get the full essentia value of the items you throw in guaranteed, as long as you're quick enough to throw in your catalysts and are careful to not use more than 19 recipes at a time so it doesn't completely empty the Crucible.  You do need quartz shards to turn the leftover essentia into a usable form, as well, but that's not bad since you can use them for making Salis Mundus or melting down later for if or when you need that essentia.

However, it is true that the Everful Urn comes a bit late.  I think it should just be an Arcane Workbench recipe similar to the Arcane Lamp.

**Comment by Goof245** [comment]
I would argue that the essentia you waste in the quartz stage is hugely more than the smelter. For every aspect you need to mop up with quartz, it's a 50% loss. The smelter is only a 10%ish loss across the board instead; you save much more essentia to use for other recipes later.

**Comment by twothe** [comment]
Also with the great new ranged transport methods for essence I just throw in a bunch of items into my smelter setup and generate hundreds of essence within seconds. What do I care about loosing a few essences if I have more than enough?

DO YOU SEE THAT PURPLE TENTACLE?! IT IS SUPPOSED TO BE THERE!! HAHAHAAHA!!!!

**Comment by terribleperson** [comment]
I do agree that the Everfull Urn isn't very useful, because infinite water is a standard feature in Minecraft. Despite this, I don't think it should stop being an infusion recipe. Permanently functional magic devices tend to require infusion in Thaumcraft, so if it didn't it would stand out from the rest in an immersion-reducing way.

**Comment by twothe** [comment]
Permanently functional magical devices like gloves, foci, thaumometer, the goggles, golems, paved stones, and so many more? None of them require infusion, so I don't think that there is any immersion broken here.

**Comment by Azanor** [comment]
This is actually a good point.

**Comment by terribleperson** [comment]
The glove and the thaumometer are passive-ish devices. I like to assume that the thaumometer is the equivalent of a piece of glass that fluoresces when exposed to vis, or something. It's more alchemical or mechanical in nature than actively magical. The glove doesn't do much without foci. Foci do seem like something that should potentially require infusion. Paving stones as well, but they're needed in substantial quantity and aren't personal gear, so without a way to mass-infuse they'd basically be worthless if they required infusion. 

I do wish there was a more detailed lore explanation for why some items require infusion and some require crafting or alchemy, so we could determine what items seem like they should require infusion from a lore perspective and which ones don't.

**Comment by twothe** [comment]
From a lore perspective: Thaumomancy is a very unpredictable art. Sometimes even complex tasks are miraculously simple, while other seemingly easy steps are impressively difficult to take. Most scholars that have tried to unravel the workings behind this have gone insane. So for now those inner details are a mystery.
