### ISSUE TITLE
[1.10.2 TC6 Beta6] Great Oak sapling grows and sapling is still there

### ISSUE THREAD

**Issue by VallenFrostweaver** [Azanor/thaumcraft-beta#347]
I placed a Great Oak sapling down and then a Nitor on top thinking it would stop it from growing. Instead it grew the tree  _next to_ the sapling. See image for details. Effectively it takes 1 sapling to grow the great oak instead of the 4 it probably should.
![tc6 tree](https://user-images.githubusercontent.com/13642054/36564929-e5782f5a-1816-11e8-8c4d-6d6efc5bb75d.png)

**Comment by jesmores** [comment]
> Effectively it takes 1 sapling to grow the great oak instead of the 4 it probably should.

Greatwoods only need one sapling to grow. I've been growing them like that since TC4.

**Comment by thenextelement** [comment]
Can confirm, to my knowledge they've never needed 4 saplings.

**Comment by MainFreak** [comment]
I agree that it should take four saplings instead of one. That gives players a bit more control about where it grows. Even if I experimented in what directions the saplings grow to full trees to find out how to set up an optimised farm, it would be a lot better (and would actually make more sense since all large variants of MC trees do the same) and easier if you just needed four of them.

And that Nitor thing looks definetly like an odd bug.

**Comment by hron84** [comment]
@MainFreak player can control where the tree grows by framing 4 dirt blocks with non-growable blocks (like bricks or sand). Greatwood - like any other wood - grows only on dirt and grass.

**Comment by MainFreak** [comment]
huh interesting

I found a vanilla bug that prevents vanilla/modded trees from growing when planted on farmland. May try that out @VallenFrostweaver

**Comment by hron84** [comment]
I've to admit I just never thought to try plant a tree on a farmland. I usually build a 1x1, 2x2 (or, for silverwood a 5x5) "pedestal" with stairs around it, and place the sapling on a correct shape. The rest is just a waiting game.
