### ISSUE TITLE
Railcraft Recipe Conflicts

### ISSUE THREAD

**Issue by Mario-Beck** [Azanor/thaumcraft-beta#355]
I have Railcraft and the latest Thaumcraft 6 installed. Unfortunately several recipe duplicates result in the Railcraft items to be crafted: brass nuggets, brass plates, brass gear and iron plates. In most cases that is not an issue because crafting table recipes accept both - Thaumcraft and Railcraft parts.
But the Golem press is another story...
I got around most conflicts via MineTweaker - setting up recipes to turn Railcraft items into Thaumcraft items. But this doesn't work with the iron plates.

Is there any way to get around those conflicts at all or make the Golem press accept more items?

**Comment by MainFreak** [comment]
I mean you can compress the recipes with mods like UniDict, but I suggest you to just turn off the nuggets and ingots in it's config (like I did in my pack). Now some Railcraft items require you to do ThaumCraft but you can't bamboozle the Thaumcraft progression with Railcraft Brass and Gears anymore.

If you decide to use UniDict for that you should set Thaumcraft as the top priority mod in it's config so recipe results are always TC (since I am not sure if some TC recipes accept ore dictionary substitutes)

**Comment by MainFreak** [comment]
How did you even manage to launch Beta 6 with Railcraft? It crashes for me because of #304

**Comment by Azanor** [comment]
I think the press ignores the ore dictionary, so that is something I need to fix.

The potion crash bug should be fixed with beta 7

**Comment by Azanor** [comment]
Actually, the golem press **does** take the oredict into account.

The listed components will be TC ones, but it _should_ still work with ore dictionary items. Is it preventing you from starting the craft?

**Comment by ScottRadish** [comment]
Just want to drop a note here that railcraft also has a void powder, that is automatically ore dictionary'd and can be smelted into void metal.
