### ISSUE TITLE
(Beta6) Epiphanies unobtainable in survival

### ISSUE THREAD

**Issue by ChaonicTheDeathKitten** [Azanor/thaumcraft-beta#357]
In survival mode, it seems like it's currently impossible to obtain epiphanies through normal gameplay.

I have read messages from several other people, stating similar problems, so I must assume, this system is bugged.

To draw a better picture.. I have scanned almost every block and item, spent hours in theory crafting and even finished the game in hopes, I'd find the missing puzzle piece (having all aspects scanned/starting all vanilla versions of mechanics like alchemy, golemancy, enchantments)
Even robbing dozens of thaumcraft dungeons and scanning all loot from chests, crates and vases didn't reward with epiphanies.
Needless to say, all normal dungeons, mineshafts, pyramids, jungle temples, end temples etc. didn't bring any results either.

Having an assortment of all aspects in form of Vis Crystals (besides taint) also didn't solve this. (Which I thought was necessary to get higher quality research?)

So far, it makes the mod working (functionally) but unplayable without using cheats.
I have been as thorough as I could. But with all the informations in the thaumonomicon, I couldn't figure out, what went wrong.

Epiphanies seemed to be working fine in Beta2. At least, I didn't encounter a barrier like this back then.

**Comment by varvolgyibeni** [comment]
i think that getting specific researches gives you epiphanies, like automated alchemy, or infusion, but atm there is a problem getting an epiphany for the golem brain research

**Comment by Azanor** [comment]
Yup, you get a tiny bit of progress from scanning stuff, but the bulk is gained by completing certain key researches.

What exactly are you being blocked from progressing in?

**Comment by darklex55** [comment]
I'm having exactly the same issue. I can't even get "Discovering Auromancy" or "Discovering Artifice and Infusion" because I can't get an epiphany (tried on multiple worlds). Alchemy is my only hope

**Comment by Azanor** [comment]
I am removing epiphanies in the next version so this should no longer be an issue. 
@darklex55  It is strange however that you are not gaining epiphanies at all

**Comment by darklex55** [comment]
After spending some hours of playing with the mod I have to say that I was wrong in the first place.

You see, I've been playing the mod since thaumcraft 3 and I was always fascinated by auromacy and - but alchemy was never my thing. I would just research the basics for the arcane crafting to work and that's it. That's why I couldn't have an epiphany. 

With the old versions of Thaumcraft, if you were stuck at somewhere, you could just find an answer on a wiki or on a forum. But since thaumcraft 6 is still in development (and generally new) I couldn't find a solution to my problem. I would scan everything. I mean it. EVERYTHING. There was no object I hadn't scanned in the overworld, nether or the end. Yet I wouldn't get an epiphany. Another problem that I had (though I don't know if it is a feature removed) is that there was no epiphany box or progress bar at the "Types of Knowledge" (I had seen it in a guys playthrough, although he didn't explain how to get one).

I'm sorry for wasting your time trying to solve a problem that (most probably) wasn't there in the first place. The only answer I found to my problem at that time was this bug report here.

**Comment by Azanor** [comment]
Not a problem :)
This post and some others did highlight the problem with gating stuff behind epiphanies so all good.

**Comment by darklex55** [comment]
I actually liked them (after I found out how to get them). They might make the path of research a liiiitle linear (forcing you to first do alchemy, then artifice/infusion and then golemancy) but it made me learn alchemy better than any thaumcraft before and generally read more to figure it out. Maybe if there was a little hint on "Types of Knowledge" so you'd know how you progress (maybe I'm just stupid :P )... Great job with thaumcraft by the way!
