### ISSUE TITLE
Can't apply a Lamp on the Bore.

### ISSUE THREAD

**Issue by NatsuArashi** [Azanor/thaumcraft-beta#459]
I'm not sure.
 Maybe it should be installed in the bore, or we just can't light up the tunnel?

**Comment by Mike-U5** [comment]
Here are my 2 cents on this:
I really like how compact the bore is now, so I would definitly support upgrading the bore with an arcane lamp rather than having to dump one next to it.

Or, just add the Arcane Lamp to the required infusion items for the bore and make it so that every bore has the lighting ability.

**Comment by Azanor** [comment]
added lamplighter infusion enchantment in b25 that should solve this issue.
