### ISSUE TITLE
scanning star Quadrants awkward

### ISSUE THREAD

**Issue by androshalforc** [Azanor/thaumcraft-beta#460]
the thauminomcon suggest that we can scan star quadrants to get celestial observations once a night.

to me this implies 4 sections for example north south east and west or something along those lines
however when testing this ive found that the scanning seems pretty awkward i can usually get 2 "quadrants" about 1/8th of the way through the night by scanning where the moon appears on the horizon. i can usually get the third quadrant in the same vicinity as the first 2 a minute or two later and the fourth one a minute or two after that in the same spot.

if this is intended it seems to me the thauminomicon entry should suggest scanning at different times in the night rather then different places

**Comment by AnrDaemon** [comment]
I did post it at the forums…

Another problem area is taking stars observations. I suggest changing it to:

 * Appropriate day time;
 * heading elevation (-90,-30);
 * heading facing [(-175,-95),(-85,-5),(5,85),(95,175)];
 * under clear skies;
 * not looking at anything specific (and not looking at the moon, obv., though with chosen headings, moon will unlikely to be in the line of sight).

**Comment by yoshiweegee** [comment]
This isn't a bug. The quadrants to which the Thaumonomicon refers are the quadrants around the Moon. Each of the four squares produced by drawing a plus through the Moon is a quadrant. This consequentially means that some quadrants are easier to scan at different times of night because the quadrants move with the Moon.

I too believe that this is not explained very well and that the explanation of celestial observation should be reworded. An illustration would certainly help.

**Comment by Azanor** [comment]
yoshi has the right idea, but I also agree that I should maybe alter how things work on my side.

**Comment by Azanor** [comment]
In the next version stellar scanning will be based on the cardinal directions.
