### ISSUE TITLE
[B9] Crash when botania is loaded

### ISSUE THREAD

**Issue by tyra314** [Azanor/thaumcraft-beta#468]
A Minecraft instance with only Botania and Thaumcraft beta9 is crashing with a class not found error. Without TC6, botania loads just fine.

Minecraft: 1.12.2
Forge: 14.23.3.2655
Botania: r1.10-353 
Thaumcraft: 6.1.BETA9

https://gist.github.com/tyra314/6033a50d3be1fe17e5d3e198f695ed0e

**Comment by Alcamore** [comment]
I encountered this as well, except it was a different error regarding Botania not being able to find the Ring of Odin item after I added Thaumcraft.

**Comment by bloowalrus272** [comment]
i received the exact same error with the Loki Ring.

**Comment by oitsjustjose** [comment]
So, at the risk of sounding like one of those "hey it's still not fixed" kind of guys, I wanted to drop by and throw a comment in.

I just built Botania from master (including the commit that addressed this bug) and it's still crashing for the same reason, but because of the OdinRing.

Not at all trying to rush, just thought I'd drop by and let you know now - I know how frustrating it is to build and release mod updates only to discover you haven't fixed it actually, and have to release another patch just minutes later.

**Comment by Azanor** [comment]
Not sure why you are posting this here though - It is something that needs fixing in botania since they have items that reference a class that no longer exists in my API

**Comment by CurePindal** [comment]
I think people might get agitated by the "wontfix"-tag. Which rather means "cantfixonthisend"..
Anyway, Botania development is already on the issue: https://github.com/Vazkii/Botania/issues/2608
All will be great and united again! =)

**Comment by CurePindal** [comment]
Aaah, Azanor... I get this very unique vibe from this new, cheeky "not my problem" tag... =)

**Comment by williewillus** [comment]
fixed in next botania build; if you're impatient, build it from the repo
