### ISSUE TITLE
[Suggestion] Option to disable Right Click to insert in Crucible

### ISSUE THREAD

**Issue by Discomanco** [Azanor/thaumcraft-beta#557]
What title says.

Just misclicked with the wrong item on the Crucible, and poof went my Tinkers pick.
Not the first item I misclick into the Crucible, but this was certainly the biggest one

**Comment by codewarrior0** [comment]
Shouldn't even be an option. This is a misfeature and needs to be removed.

**Comment by fingersome** [comment]
Yeah this is by far the most annoying "feature" of the crucible. I have melted uncountable empy buckets thanks to this

**Comment by Dragnier** [comment]
Perhaps an adjustment to Shift+Right-click to put things into the Crucible? That way, the feature is retained for those that use it and isn't annoying for those that dont.

**Comment by wamc2017** [comment]
Please don't change the current right click behavior, it's nice for automating the crucible with fake players.
An config option would be a better solution (if pack makers or players don't want this behavior...)

**Comment by Lukas45** [comment]
Shift+Right-Click would be a bad idea, since that's force use item, instead of interaction with block.
Shift-Click maybe?

Can't you just use a dropper instead of Fake Players?
The amount of buckets I have lost because my mouse is starting to wear out and causes double-rightclicks on single clicks... :/

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#389
