### ISSUE TITLE
[Suggestion] More verbose warnings about taint and/or a taint detecting (warning) device please.

### ISSUE THREAD

**Issue by Geethebluesky** [Azanor/thaumcraft-beta#681]
I'm leaving this here with the assumption that taint-fixing is a mechanic that isn't finished and there should be ways to deal with it later in the progression, or that balancing is yet to be completed. (?)

That said, I respectfully suggest that in certain conditions (depending on what mods, playstyle etc. you have), taint as it is right now is OP and world-breaking.

- I was warned about overall taint behavior by another user; nothing in the Thaumonomicon really impressed onto me that "if you don't let flux dissipate and space out your operations, or move somewhere else, YOU WILL LOSE YOUR BASE."

- After making a mistake and seeing taint for myself, I ended up in the situation where taint was consuming the main tower at a backup base. There was nothing in the Thaumonomicon to tell me "look above" and so I was running around after seeing purple clouds, wondering if the spawn would occur in my basement or anywhere else. The range of Taint 2 and 3 is also long enough to make me think it was on my main floor but ... nope, it was about ~15 blocks above me. By the time I found the problem zone, it was too late. "By the time" in this case = 20 IRL minutes. 

- I play with mods that debuff when your health gets too low; Taint Poison 3 nabs over a heart per second, making me instantly too weak to destroy even a single taint block. Game Over for that base, even after being forewarned _outside_ the mod. (Config for this maybe? Or a slower progression from levels 1 to 2 to 3?)

- I play with Gravestones; it stops being a simple matter of running fast enough to grab all my stuff and try again. I need to break a block to reobtain my things, but by then taint was too powerful for me to even do so. If I need enchanted armor to survive taint, and all I have are backups that I run out of... yes, this might be a problem with my playstyle but again, nothing in the Thaumonomicon impressed on me that "yeah you need to have a double stack of top-tier regen potions" before dabbling with the Crucible, which is fairly early-game IMO.

To solve some of this I'd like to suggest **a device similar to the Compass**, that can detect where taint may occur "should conditions continue to worsen". The code already knows the general location of where it will spawn a taint seed or critters, so it should be possible to give the player some kind of ability to run faster to where the problem would occur. It's in the same spirit as the Sanity Checker... I'm able to see if I'm going nuts before I'm completely gone googoo gaga, well I should be able to **see** that I'm ripping the world apart before it's uh, _done_.

Other suggestion would be to have something much more serious happen before taint seeds itself... because frankly, by the time that happens? Cthulhu's come out of the sea, so to speak. The cauldron overflowing and purple clouds only meant something to me because I knew of them in advance, but they don't give the impression that it would go from zero to 300 in less than 20 minutes.

Like I said, just suggesting these to get a discussion going, though.

**Comment by Gravityowl** [comment]
Currently i think taint is a little weak and doesn't off much of a challenge the main problems I've had with it is just when the flux rift spawns somewhere really inconvenient where you wont be able to attack it from range.

the Seed can be attack by a bow and arrow fairly easily from a good distance away, this of course doesn't really apply if it spawns in your base or around walls, also you can locate the flux rift before the taint seed spawns with the goggles of revealing, they will let you see the rift through walls. As for warnings one is given when a flux rift spawns, I think. I believe I've spotted it briefly but each time i happened to be trying to scan things with the thaumometer.  but to be fair it should probably be a little more severe of warning and not something that can be missed by scanning with the thaumometer

Taint Poison III is way to punishing to get right off the bat for even getting close to the seed, its enough to go through any saturation you have built up and then half of your health bar, if not more if you happen to stand around in the taint for more than 3 seconds. Id like to see fighting the taint more melee based because at the moment you have no reason to set foot in the taint unless you want to instantly die. which is a shame because you wont see any of the taint creatures or even fight them because the seed was shot to death by a bow from 50 blocks away. if you had fight it from melee you'd see the taint popping its flux reserves, crawlers spawning and chasing you out of the taint spreading even more, having to back off when the poison got to high and trying to stand on non tainted blocks to avoid taintacles. I think that'd be cool but for that to work the seed would have to be immune to ranged attacks  and not put a debuff on you that's effectively a death sentence if you have anything less than full health

In regards to the crucible pollution I personally i don't have a problem preventing taint, I use quartz slivers to take essentia out of the crucible to not waste and pollute, and warded jars to remove any from the alembic. I've had to create taint on purpose however to move past essentia piping, because it needs a phial with vitium in it. which in my opinion i think is good because it forces the player to at least encounter taint before moving forward, thus letting them know of the potential danger

The spawn location of flux rifts can really be troublesome the larger your base is. If the flux rift were to spawn farther away to give people more of a chance to locate it but also be larger (I've seen how large a flux rift can get and they are truly frightening when they are at their max) then i think that would get rid of the potential situation of a flux rift spawning in your backyard, as well as give a very large and fair warning to the player, then speeding up the rate at which taint spreads that way its still a danger. but one that can be managed if dealt with quickly before it gets out of hand

Overall i don't know where the taint as a whole stands development wise but at the very least I'd really like to see the taint poison turned down a couple notches so it doesn't doom you as soon as a taint seed spawns

**Comment by EvilOtter** [comment]
A spamable but expensive early game taint/flux mitigation system paired with a later game solution would be a reasonable compromise. Accidentally emptying a single jar of essentia is enough to cause real havoc. Building an island of glass in the ocean for alchemy seems like an exploit but when it's so easy to cause flux pollution there aren't many other options. Something like a destructible silverwood, gold, and vis crystal totem would a reasonable early game mechanic and a infused device that requires a fuel would be good for later game base preservation. I'm just spitballing ideas and I do like the flux/taint system but a couple of ways to deal with it are really needed.

**Comment by enderger** [comment]
Taint needs to spread into other chunks and, when leather is at a shortage, it can be very hard to see a flux rift

**Comment by enderger** [comment]
Shouldn’t this go here... 
https://github.com/Azanor/thaumcraft-suggestions

**Comment by enderger** [comment]
Also, the taint seed has a hit range of about one floor in a village church, and I had to go into GMC to recover the church in my ssp world when the nitor glitch caused a taint rift to spawn

**Comment by enderger** [comment]
Alchemical mistakes may also need to be more forgiving

**Comment by Geethebluesky** [comment]
There seem to be a couple different things to push you to get tainted/get Warped as you progress, alchemy blunders being one of them... I think that's kind of normal, but the results are just so massive when you're starting out. I have all the equipment I need to combat taint infestations at my main base now but Taint Poison III is still insta-death, and its effective range is way beyond where taint has actually spread it seems.

I don't get it. Is there progression that can only be unlocked if you're **killed** by taint, coming in later betas?

**Comment by Gravityowl** [comment]
Following up on what I said earlier about taint spawns being really annoying if they show up in inconvenient locations, I've found it immensely difficult to automate anything via pure thaumcraft. Due to the unavoidable flux build up and with no way to mitigate it even with 3 vents on an essentia smeltery I'll still eventually spawn a flux rift. This is disastrous for automation because it can break blocks, sometimes destroying the entire system, and if you have any golems working in the area then you can say goodbye to them when the taint seed spawns

**Comment by Gravityowl** [comment]
Following up on what I said earlier about taint spawns being really annoying if they show up in inconvenient locations, I've found it immensely difficult to automate anything via pure thaumcraft. Due to the unavoidable flux build up and with no way to mitigate it even with 3 vents on an essentia smeltery I'll still eventually spawn a flux rift. This is disastrous for automation because it can break blocks, sometimes destroying the entire system, and if you have any golems working in the area then you can say goodbye to them when the taint seed spawns

**Comment by Gravityowl** [comment]
Following up on what I said earlier about taint spawns being really annoying if they show up in inconvenient locations, I've found it immensely difficult to automate anything via pure thaumcraft. Due to the unavoidable flux build up and with no way to mitigate it even with 3 vents on an essentia smeltery I'll still eventually spawn a flux rift. This is disastrous for automation because it can break blocks, sometimes destroying the entire system, and if you have any golems working in the area then you can say goodbye to them when the taint seed spawns

**Comment by Geethebluesky** [comment]
There might be ways of getting rid of flux later though, I've seen a bug report with some sort of sponge in hand, but have no clue how that person got it...

**Comment by enderger** [comment]
Wait... Aura Nodes could be implemented as slow aura purifiers that eat flux and refill it with "blank vis" that cannot be harnessed

**Comment by Geethebluesky** [comment]
I'm not a fan of aura nodes in general so I guess I'd rather see what else is left to discover between now and a release. There'll probably be some flux mitigation mechanisms in the works or such.

**Comment by Darkmega18** [comment]
maybe.... a way to generate your own space-time rips and suck the flux into the void yourself? or... a flux vacuum multiblock apparatus that once built consumes vis to suck in the flux from a 3x3 chunk area and just turns it into vitium shards or something. :D

**Comment by Geethebluesky** [comment]
I would be stoked to find out part of the Void/Eldritch stuff is controlling rifts. And have them be portals to the Eldritch itself... That would be rad!

**Comment by enderger** [comment]
The spounge came from creative mode

**Comment by Raumis** [comment]
The Thaumic Dioptra already shows vis/flux levels, and it gives off a redstone signal.
