### ISSUE TITLE
research involving vis crystalls

### ISSUE THREAD

**Issue by hollowhalls** [Azanor/thaumcraft-beta#686]
hello, just installed your mod on a server with a few friends and it seems all the research dealing with a vis crystal is very picky on where the crystals are.. for instance on the essentia smelting research  you can have all the primal crystals in your inventory but the book wont recognize them, or only be able to recognize a few. i saw a post saying something about the book not saying  what crystals you need but nothing about inventory detection.

**Comment by Moholmarn** [comment]
I've got the same issue. It seems to detect the crystals in the hotbar, but only sporadically in the inventory. Sometimes it even depends on if you enter/exit the thaumanomicon fast enough. Sometimes it detects all the crystals but doesn't complete the research even of you click the button. As of now i'm stuck at "completing..." rather than a detection error.

**Comment by Azanor** [comment]
Is this still occurring in the latest versions? I remember fixing this bug a while ago.
