### ISSUE TITLE
[B13] Filling Essentia Transfuser not filling proper jars

### ISSUE THREAD

**Issue by EightOneFive** [Azanor/thaumcraft-beta#704]
Have 3 Filling Essentia Transfusers sitting on a single Alembic on my Smeltery (left, right, back). When I go to smelt an item it appears that when filling the jars around my smelter it doesn't go to the labeled jar 100% of the time, some of the time it will send some of the essentia to a random blank/empty jar on the opposite side of the smelter where the labeled  jar is. although the labeled jar is well within distance and has plenty of room in it.

**Comment by apmax** [comment]
I would assume that's because you're splitting the essentia 3 ways in 3 different directions when probably only one of the transfusers in one direction has access to the correct jar.

**Comment by EightOneFive** [comment]
That was my thought as well, but wouldn't it make more sense for the Alembic to look at all three Transfusers that are attached to it and see if it already has a path to a jar with the same essentia and/or a label before it spits it out? Or am I missing something? Was under the impression these were put in place to remove the need for tubes or the jar filling golems of old.

**Comment by apmax** [comment]
If there's an empty jar in the range of one of the transfusers, then that's a valid place for your essentia to go, isn't it.   It seems like intended behavior for the transfuser to place essentia into empty jars, I don't think this is a bug as much as your setup is just non-optimal.   Label all your jars OR stop pointing multiple transfusers in different directions with empty jars in front of each of them, and you'll stop seeing this essentia distribution problem.

**Comment by EightOneFive** [comment]
Yes, an empty jar is a valid place, but would a labeled jar not take favor over a non-labeled jar? I would understand that if a new essentia type is being put into a jar then it would find the closest non-labeled jar. But when I have a labeled jar with 157 aer and smelt something with aer, you would assume it would target the labeled aer jar, and not an empty one.

In regards to the multiple transfusers, it appears to be the only solution I can find. When smelting an item it first breaks down the essentia into the smelters hopper. It then releases the first essentia into the first alembic. If that alembic has a transfuser on it the first essentia is immediately shot out to a jar, meaning the next essentia fills the first alembic again and does the same. You can't have multiple alembics on top of the smelter if you are using a transfuser (that I can find). So unless you want a wall of jars on a single wall with a single transfuser pointing at them, you need multiple transfusers.

At the end of the day I'll have all essentia labeled and in jars so this (likely) won't be a problem, but it just seems broken that some essentia doesn't get placed 'properly'. And it's just a pain in the butt when you have to dump 1-9 essentia into flux because you can't draw it with a phial from the jar to make it empty.

**Comment by apmax** [comment]
A transfuser attached to an alembic containing essentia looks for a valid jar, finds the nearest empty jar because there is no matching labeled jar, and moves the essentia.  A transfuser on the other end of the alembic has no bearing on this one's function, and so will also draw essentia from the alembic to fill any jars within its field of view.  All the alembic is doing is outputting essentia to attached devices.  This situation as you are describing it is not a bug.
You can put the transfusers on valves so you can turn them on and off, you can create your setup so that there is no ambiguity in which direction essentia can go by putting a transfuser on each alembic facing in the same direction with access to the same jars, or you can simply label all of your jars.

**Comment by EightOneFive** [comment]
Not sure which part of this I'm not communicating properly...

*The jars are labeled*

-I have void jars to the left, right, and behind the smelter. Some labeled that have essentia in them already, some empty without essentia.

-I have a labeled jar of Victus to the left of the smelter. 

-I put rotten flesh into the smelter. The first essentia to break down and transfer is Victus.

-The Victus does not flow out the left transfuser to the labeled jar, instead it flows out the right or back transfuser to an empty jar. 

-This does not happen every time.

-This has happened with multiple types of essentia, all with the same setup. Labeled jars on one side, essentia fills up an empty jar on the other side instead of the labeled jar.

-This does also happen with non-labeled jars (whether this is a bug or not). If I break down stone, the terra goes to an empty jar (which makes sense). If I do it again, the terra will go to a completely different unlabeled jar. If I do it a third time, the terra will go to the first unlabeled jar that has terra in it.

**Comment by EightOneFive** [comment]
https://ibb.co/iYGKmJ

Here is what I'm talking about, just caught it in the act, this time from the SAME direction transfuser (behind the smelter) and the labeled jar was right beside the empty jar that the essentia actually filled.

1) labeled jar of Humanus behind smelter, labeled Victus to the left, labeled Perditio to the right.
2) put rotten flesh into smelter 
3) Humanus essentia filled up the unlabeled empty jar right BESIDE the labeled jar. 
4) Victus went to the proper labeled jar to the left of the smelter
5) Perditio went to the proper labeled jar to the right of the smelter. 

Again, this does not happen every time. Just tried it again (after emptying the unlabeled Humanus jar) and everything worked as it should.

**Comment by EightOneFive** [comment]
And here is it again, different ingredient:

https://ibb.co/jqD5bJ
https://ibb.co/ieOXOy

1) labeled jars of Ignis and Potentia to the right of the smelter.
2) put coal in smelter to break down (Ignis and Potentia aspects) 
3) Both the Ignis and the Potentia did not flow to their labeled jars to the right, instead both flowed out the left transfuser and filled two unlabeled jars behind me.

**Comment by apmax** [comment]
You're communicating your issue properly, the problem with it is that _the transfusers are working as intended and filling valid jars within their field of view_.  One transfuser does not wait and ask all other transfusers attached to the pipe network if they have a labeled jar they can see before deciding to distribute the essentia itself.   As the alembic fills up, whichever transfuser acts first distributes the essentia it has access to into whatever jar it can find.  What I don't understand is what you think is unusual about this behavior.   If you want a specific transfuser to place certain types of essentia into the jars you have labeled that it can see, make sure no other transfuser on the pipe network can see unlabeled jars which could accept the essentia.  
Again, I think this is more of a filtering issue in your essentia distillation setup rather than a bug with the behavior of essentia transfusers-- if you label your jars this entire problem disappears.

**Comment by EightOneFive** [comment]
Yeah...that still doesn't explain my first image with it putting the essentia in an unlabeled jar right beside the labeled one...

Let's just wait for Azanor to confirm whether or not this is intended or not.

**Comment by apmax** [comment]
Your original issue involving multiple transfusers seems like nothing more than an inefficient smeltery arrangement, but if a single transfuser is filling unlabeled jars before labeled ones it could be an issue with jar priority.  I would imagine a single independent transfuser should target labeled jars before unlabeled jars within its field of view.  Are there any special conditions for which jar wrongly gets filled first?  It might be based on cardinal direction or something along those lines.

**Comment by 63502** [comment]
Correct me if I'm wrong here, but in relation to the first image the problem you seem to be experiencing is that essentia can enter any transfuser with a valid output jar be it labeled, unlabeled, or void at random __including overlapping distribution areas__. The side and back transfusers respective areas overlap on the unlabeled jar, while only the back transfuser has access to the labeled jar. Since distrubution to valid outputs is random when multiple transfusers have valid outputs, essentia only reaches the labeled jar if it starts flowing through the back transfuser first. If it goes through the side transfuser, like shown, it goes to the unlabeled jar.
