### ISSUE TITLE
[B13] alchemical brass has no recipe

### ISSUE THREAD

**Issue by galenr150** [Azanor/thaumcraft-beta#725]
alchemical brass literally just doesnt have a recipe for me. i even made a creative world, unlocked all recipies, and just nothing shows up. i click on it on the thauminomicon and it just gives me a blank page where the recipe should be.

i have the following other mods enabled:
baubles
better fps
botania
inventory tweaks
iron chests
journey map
JEI
quark
roots
thaumic periphery
twilight forest
tinkers construct

**Comment by Drou45** [comment]
the problem is with iron chests ... and everything that implements something from that mod

**Comment by garpu** [comment]
So alchemical brass isn't craftable with iron chests? I dumped instrumentum into a crucible, then tossed in iron, and the iron didn't produce brass. (It just made whatever element iron is.)

**Comment by apmax** [comment]
A quick google search shows that this "Thaumic Periphery" mod in your modlist changes the recipe for brass, requiring copper instead of iron.  That mod may not be registering the changed recipe correctly.

**Comment by galenr150** [comment]
yes, removing iron chests fixes it for some reason.

**Comment by xenxero1** [comment]
I believe IronChest's add's in a copper element, but no actual ore. ThaumicPeriphery likely checks to see if copper is an available resource, and changes it's alchemical brass if it is.  You should just disable the copper override in the Periphery config, otherwise whenever another mod adds copper, you will run into the same issue all over again.
