### ISSUE TITLE
Crash when using thaumic spells on other players

### ISSUE THREAD

**Issue by Xules01** [Azanor/thaumcraft-beta#729]
Thaumcraft-1.12.2-6.1.BETA12

It is inconsistent, but when casting a spell (I've had it happen with healing and flux) at another player, it crashes both parties clients.  The logs I have are all from my side, being the one casting.  If needed I can try to get the receivers reports too.

Reports:

[crash-2018-05-11_02.19.41-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1995910/crash-2018-05-11_02.19.41-client.txt)

[crash-2018-05-10_00.50.49-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1995911/crash-2018-05-10_00.50.49-client.txt)

[crash-2018-05-10_00.20.17-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1995920/crash-2018-05-10_00.20.17-client.txt)

**Comment by Geethebluesky** [comment]
Does this happen with Beta 13 as well?

**Comment by Xules01** [comment]
Yes, it caused a crash on my side when I tested in Beta 13 as well.

**Comment by TyphonsShadow** [comment]
I had this same occurence.  I believe it has something to do with the way projectile targetting works.  The errors we got were all regarding it not being a correct entity.  When we set the projectile target to none instead of hostile/non-hostile, it worked fine.

Crash log:

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at thaumcraft.common.lib.utils.EntityUtils.isFriendly(EntityUtils.java:48)
    at thaumcraft.common.entities.projectile.EntityFocusProjectile.func_70071_h_(EntityFocusProjectile.java:196)
    at net.minecraft.world.World.func_72866_a(World.java:1990)
    at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
    Entity Type: thaumcraft:focusprojectile (thaumcraft.common.entities.projectile.EntityFocusProjectile)
    Entity ID: 174304
    Entity Name: Focus Projectile
    Entity's Exact location: 367.15, 93.85, 1100.89
    Entity's Block location: World: (367,93,1100), Chunk: (at 15,5,12 in 22,68; contains blocks 352,0,1088 to 367,255,1103), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
    Entity's Momentum: -0.92, 0.19, 0.13
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1756)
