### ISSUE TITLE
Research expertise

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#80]
Will this research be making a comeback? If so, there are a few different researches/specializations that could branch from it, given the new changes to the research system. Some could be mutually exclusive or have previous requirements.

- Inspired
Grants bonus starting inspiration

- Thorough
You draw 3 instead of 2. Bonus draws increase your draws to 4.

- Analytical
You gain more insight from draws that require no components, and less from those that do.

- Experimental
You gain more insight from draws that require components, and less from those that don't.

- Unorthadox
You gain more insight from draws that increase your warp, and you have additional chances to gain warp from your draws.

**Comment by Azanor** [comment]
Research expertise is built in now. The more research you unlock, the more inspiration points you have.
I was toying with certain expertise type unlocks, but most of them turned out to be pointless, or made research too easy. Some of those ideas are interesting though. I might revisit adding something like it at some point.

**Comment by Azanor** [comment]
This issue was moved to Azanor/thaumcraft-suggestions#165
