### ISSUE TITLE
[B13] Am I dumb? What am I supposed to do? (taint)

### ISSUE THREAD

**Issue by applebaps** [Azanor/thaumcraft-beta#800]
Early on in learning the TC6 changes, I was experimenting with alchemy, and got a quest advising me to "let the Flux build", so that's what I did.  Turns out it tore a hole in reality outside my house.

![2018-05-15_18 54 42](https://user-images.githubusercontent.com/39362356/40265945-41e67fc0-5aee-11e8-8d4f-a54f67186d39.png)

Now, a few minutes later, it looks like this:

![2018-05-18_22 50 32](https://user-images.githubusercontent.com/39362356/40265929-e689e662-5aed-11e8-8ddb-62d0a904625d.png)

I tried planting silverwood trees nearby after seeing online and recalling from previous TC versions that they reduce flux, but after monitoring the level in the aura for a while, they don't seem to be doing anything.  I guess without nodes, there are no "pure nodes" anymore.

The page on Flux now advises me I should "look into ways to minimize flux", but gives no further information as to how to do that.

After running away into exile to do more research, looking around for ages for new materials, scanning everything I could find, and dying way more times than I care to count (losing several thaumometers and thaumonomicons in the process), I finally managed to get close enough to the tainted seed to scan it, and I get this text:

![2018-05-18_22 52 04](https://user-images.githubusercontent.com/39362356/40265940-26106e50-5aee-11e8-84cf-a90b27e3a5a6.png)

There's a problem, though.  I can't get anywhere near the seed at this point, because the taint has spread far enough that if I come close, I get this insane poison that kills me almost immediately.  If I just rush the seed and start swinging, I die after getting one or two hits in.  But then I lose my weapon.

I get that ranged attacks might be better (though I also lost my caster's gauntlet early on, when the seed formed outside my house and somehow I got taint poison on me INSIDE the house before I realized what was going on), and that this isn't exactly a "bug", but I wanted to lodge a complaint, I guess, related to how this all gets handled from the player experience POV.

Right now, the text in the Thaumonomicon encourages the player to raise the level of Flux in an area.  That might not be the greatest idea, especially considering how crazy the taint seems to be in 6.  Additional guidance might be warranted as to how to remove or reduce Flux or Taint, also, since right now the only guidance I have from the book (which has otherwise been really good about walking me through everything) is to kill this seed, which I can't do.  It's also not entirely clear what's going on with the Taint Poison II effect.  I'm not touching a tainted block when it hits me.  Is it supposed to be from the tainted air?  If so, how am I supposed to deal with this at all?  Is my house just done for?

I like that magic has this air of danger to it now, and that the cost is higher for dabbling in what you don't understand and being careless.  But imo this is a bit much.  The player shouldn't be punished so harshly for following directions.

I would also like to note that the framerate near my house dropped into slideshow territory after this happened until I disabled TC's shaders.

Granted, this made for some great motivation and a fun little adventure.  But it's only really THAT fun if I can eventually overcome the adversity and succeed, lol.

**Comment by Gravityowl** [comment]
Ya at the moment I don't believe there is a way to evade taint, even with precautionary measure, it will eventually happen, I think this is because flux just doesn't go down, there's a moderate issue opened about at #681 with a bunch of suggestions and ideas for balance, and I also agree the poison is way too high.

**Comment by Geethebluesky** [comment]
The only way I've found of dealing with a Taint seed so far is to 1. not deal with the seed at all: wrap the general area of the rift in a small lava pond before the seed sprouts, the lava just kills the seed upon spawning.

Or 2. get really good with a bow and kill it at range. Not possible if the seed is indoors anywhere though so... Yeah.

**Comment by applebaps** [comment]
FWIW you can tweak taint spread in the mod options. setting both parameters to 0 is "wuss mode".

**Comment by Geethebluesky** [comment]
Yeah but you can't currently alter the range or strength of the Taint Poisons AFAIK.

**Comment by Sumguy62** [comment]
Liberal application of TNT works wonders.

**Comment by redgoblin88** [comment]
when you make taint it will build up but once it reaches a certain threashold it will create one of these "rifts" which act something like a black hole or a sun in wehich it slowly voids the taint (very VERY slowly may i add) and eventually it will return back to normal levels however the more bad the taint level is, the worse damage it does to the environment and has a higher chance to spawn monsters through the fracture.

note however that the taint is only in one chunk but it does spread to other chunks but at a rate that is almost ignorable unless its over 3,000.

playing on a server with my friends, we get taint crystals through this method by throwing all sorts of junk into a crucible and then breaking it. we did this in the mining world and waited for the "fun" to start happening but as soon as i saw a taint seed spawn i said "run... just RUN!" but they all hesitated and died. when they tried to retrieve their corpses they couldnt get within 32 blocks(ish) of it but i told them that you have to use a ranged weapon like a bow.
after a while whisps started to spawn and they were VICIOUS!
but hey.. least we got the crystals!
(oh and a final note... it was over 10,000 taint which made the thaumic dioptra spike almost go outside of the block!... yeah took too many hours to clear away so the owner removed it with a creative "sponge")

i think that using a "bolt" spell may not be far enough reach to the spores since it only does a 16 block range and im not sure if the thaumic crossbow will work however other ranged weapons such as a bow definitely work and is highly advised against the spores/seeds and i would also reccoment the thaumcraft bolt weapon against wisps as it has near nstant impact with no delay.

**Comment by Raumis** [comment]
Liquid death works nicely
