### ISSUE TITLE
Why switch from base 2 to base 5 for counting essentia?

### ISSUE THREAD

**Issue by ViciousVinnyD** [Azanor/thaumcraft-beta#854]
Thaumcraft 4 used 8 as a base number for counting it's essentia, which makes perfect sense as it's a widely divisible number and flows well with how minecraft stacks items in 64. This new system seems rather illogical and makes counting out alchemical ratios slightly more difficult as it conflicts with minecraft's 64 stack limit.

**Comment by apmax** [comment]
The amount of essentia on items has also changed and the new system is effectively much simpler.
Instead of requiring 3 of one item and 2 of another plus the catalyst, you only need one, one, and the catalyst.  You shouldn't really be doing alchemy involving whole stacks of items unless you want your crucible to overflow, anyway.

**Comment by MalkContent** [comment]
My main gripe is that the Jars storage cap isn't base 2 anymore :/  
Other than that, I don't mind the alchemy stuff having hard to figure out ratios to do lossless alchemy in the crucible. Either you spend a good bit of time figuring something out or you go "aaa, how bad can a liiiittle bit of flux be", which I feel is very much in the spirit of the mod. Makes the creation of a certain amount flux a byproduct of general unoptimized operation instead of a byproduct of the user messing up.

**Comment by Geethebluesky** [comment]
Issue being there isn't any obvious way of managing flux at the moment, and the consequences of it building up are out of proportion (catastrophic unless you're lucky, basically) with it being a mandatory part of the progression.

**Comment by apmax** [comment]
I've had no major problems dealing with flux buildup.  Unless you're dumping hundreds of essentia on the regular, a single rift will spawn, create a single taint seed, and then vanish harmlessly.  As long as you have a fireball focus or something like that before you get too deep into alchemy, and provided you deal with them quickly, the taint seeds won't be a problem at all.

A better way to manage flux would be much appreciated, more mechanics surrounding rifts maybe, but as it is now all you gotta do is be slightly careful and proactive.

**Comment by ViciousVinnyD** [comment]
I'm not bothered by flux, I'm just questioning the logic behind switching from base 2 (which minecraft already uses) to base 5.

**Comment by apmax** [comment]
It was only ever _really_ base 2 in the context of jars and vials.  Before, items and recipes had aspect numbers in units of 1s or 3s or what have you.  It's a lot more uniform now, pretty much everything is 1, 5, 10, or multiples thereof.  Even jars and vials, so the amounts contained in vials and such now more closely match the values required for doing alchemy.

**Comment by MalkContent** [comment]
I'll have to really play TC (as opposed to just trying to break it in creative) to make my mind up about how these new round numbers make alchemy feel more wonky (which would be a good thing imo), due to not being able to cash in on the factor 2 that easily. But for now I really don't like it because it's just a paradigm break with the rest of how minecraft counting works.
