### ISSUE TITLE
Cloud stepper ring.

### ISSUE THREAD

**Issue by red360** [Azanor/thaumcraft-beta#939]
TC Ver B13 mod interaction with Enderio dark steel armor jump and viesCraft ascend.
When any other mod has a key assignment to jump (spacebar) ring does not double jump.

**Comment by redgoblin88** [comment]
err could you explain in a tiny bit more detail? such as does it make you jump up twice as high? do you keep on juping upwards? do you shoot off towards the skies (like hundreds of blocks in one jump)? do you not jump at all (like they negate each other so the boost is not applied)? with enderio does this issue still happen regardless if they are charged or not (because when theyre flat they are meant to stop doing the jump)? is it only the spacebar jump (tried re-binding it)? what versions are the other mods? what version of forge have you got? are you sure its only these three mods and not any other additional mod causing some quirky behaviour?

**Comment by AnrDaemon** [comment]
> When any other mod has a key assignment

WAD
When you have more than one action attached to a single shortcut key, the results are undefined.

**Comment by Azanor** [comment]
On my side I just check if the jump keybind has been pressed - I do not check specifically for space. If you have multiple things assigned to the same key you should except odd behaviour.
