### ISSUE TITLE
[B16] Thaumatorium getting gummed up, pulling more essentia than recipe needs

### ISSUE THREAD

**Issue by Geethebluesky** [Azanor/thaumcraft-beta#953]
Long story short, the Thaumatorium seems greedy and pulls more units of essentia than the currently-selected recipe needs.

I had it previously set up with a single emptying transfuser, currently producing clusters from iron ore.

For some reason now, the transfuser is always pulling 1 extra Metallum that ends up blocking the pipe, since the recipe only needs 5 units and now there are 6 in the machine. This means Ordo can't be pulled until I remove the pipe with the extra essentia unit and put it back.

To try to avoid this I set up another emptying transfuser on another side... but now both sides just end up gummed up with Metallum in the same way.

Not sure if this is supposed to be desired behavior in TC6 but it sure looks like a bug to me!

**Comment by yunruiwatts** [comment]
I've noticed this with pipes even in TC5 - it pulls more than it needs to, but as long as you've still got the jar connected it will pull the excess essentia back into the jar. If you're using an emptying transfuser, there's no connection for the essentia to go back into the jar.

One way you can solve this is to connect the emptying transfuser directly to the Thaumatorium - it doesn't pull in any extra essentia this way. Another way is to connect a filling transfuser so that there's a way for the essentia to get back into the jars.

**Comment by Azanor** [comment]
This is how things are supposed to work. Essentia tubes and the suction mechanics have their own unique charm.
