### ISSUE TITLE
[B16] Taint kills Taintacles

### ISSUE THREAD

**Issue by katzenpapst** [Azanor/thaumcraft-beta#954]
Title says it all. I started a taint experiment. A rift opened, a taintseed grew and attacked me with taintacles... which showed those purple particles and died. I think this isn't supposed to happen :D 
It also happens to wisps. Which come out of the rift, which still didn't close, despite the taint seed. Is that a bug, too?

**Comment by Reassembly** [comment]
The appearance of a taint seed no longer closes the rift that spawned it, as of b14. Kind of vicious, since it means that rifts are now permanent once they appear, but it seems intentional.

Taintacles seem to despawn when the player steps too far away from the tainted soil they're rooted to - is that what you're seeing? Or are the taintacles dying from taint even when you're close by?

**Comment by Azanor** [comment]
The little taintacles are supposed to be short lived and don't survive long if they aren't on tainted ground.
It is intended that the rifts no longer close when taint seeds spawn.

**Comment by Lukas45** [comment]
@Azanor What will that mean exactly? That there will always be a rift in that chunk? Will it continue to grow over time? Can multiple spawn?
Or are there ways to deal with it yet?

**Comment by katzenpapst** [comment]
Is there a non-cheaty way in B16 to get rid of the rift? If not, I'm just going to use the taint sponge. If yes, could you give us a hint at least? Scanning the rift doesn't do anything.

**Comment by wamc2017** [comment]
As stated by Azanor, there will be a way to handle those rifts in the next non-bugfixing update...

https://github.com/Azanor/thaumcraft-beta/issues/922#issuecomment-394286769

**Comment by katzenpapst** [comment]
So, for now, the taint sponge it is.
