### ISSUE TITLE
Creating aura cache for world -1 {Spam console}

### ISSUE THREAD

**Issue by epeeforteyt** [Azanor/thaumcraft-beta#966]
Hello, the problem comes from some version of the mod, but the major problem, comes from the fact that it really spam side server console but also can crash, and the ram allocated increases as and when.

[latest.log](https://github.com/Azanor/thaumcraft-beta/files/2074644/latest.log)

Forge version: 1.12.2-forge1.12.2-14.23.4.2707
Thaumcraft: Thaumcraft-1.12.2-6.1.BETA16

**Comment by Azanor** [comment]
I am 90% sure the cause is not TC. Something is repeatedly causing dim -1 to be loaded and then unloaded. The aura cache message will appear whenever that happens, but it is not actually causing the underlying problem. Nothing aura related happens until a dim is loaded and auras cannot cause dims to be loaded themselves.

I will take a look anyway however.
