### ISSUE TITLE
Golem Harvest Seals don't work well with pam's harvestcraft plants

### ISSUE THREAD

**Issue by drachs** [Azanor/thaumcraft-beta#991]
These plants aren't designed to be broken, as a matter of fact most plants aren't designed to be broken anymore.  I think the harvest golem would work much better if it right clicked on the plants instead of breaking them.  Maybe an option for an advanced harvest seal?

In any case, when mature plants are broken they don't usually drop seeds they drop fruit.  You can convert some of the fruit into seeds.

**Comment by Geethebluesky** [comment]
> Maybe an option for an advanced harvest seal?

I can't second this enough; in TC5 I couldn't automate a Harvestcraft farm due to this issue either.

It's not just limited to Harvestcraft either: Simply Corn also has the option to harvest without breaking the crop in its config file, and drops corn (not seeds). Natura also has barley and cotton among others, which are right-click-harvestable. 

Seems to be a pretty standard mechanic in modded MC these days.

I suppose golems can use an autocrafting table to make seeds from the various crops if they're broken, since those are usually a 1:1 recipe. But that would afterwards require a seal that's able to tell the golems to plant a specific crop in a specific location (planting seal?) In TC5 I couldn't get golems to plant crops where I wanted them and in the number I needed, they just planted randomly it seems.

**Comment by erdemozor** [comment]
They are also having trouble with agricraft seeds and crop sticks, breaking them even when the plant hasn't matured. And some they don't even recognize, like watermelon seeds in cropsticks.

**Comment by Azanor** [comment]
In my api I have a IMC function that allows mod authors to set their crops to be click-harvestable by golems. Pam's used to have that, but I guess they might have removed it at some point. Maybe go remind them that it is a thing :)
